### ISSUE TITLE
Seccomp: Improve syscall allow-listing / deny-listing Process

### ISSUE THREAD

**Issue by dhrgit** [firecracker-microvm/firecracker#1008]
Our current syscall whitelisting process doesn't guarantee that all legit syscalls make it past the seccomp filter. We need to devise a model that can guarantee any seccomp infringement is caught, at latest, during our testing phase.

**Comment by alindima** [comment]
This issue was aiming at using static analysis for devising the seccomp allowlist.
If we did this for the Firecracker binary, that statically links musl, we'll get a huge number of syscalls, some of them being unreachable from normally-functioning Firecracker, essentially making seccomp filters useless.

Also, simulating every type of customer workload in the CI is not feasible.

Closing this issue for the above reasons.
