### ISSUE TITLE
does patching a drive takes some time before ready to use

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker#1159]
When patching a drive and mounting that drive immediately in the VMM seems to return an `invalid argument` error, occasionally. This signifies that there is a race somewhere and was wondering if the patch drive operation takes some time to populate to the VMM before being ready to use.

We have an open [issue](https://github.com/firecracker-microvm/firecracker-containerd/issues/214) with more information.

**Comment by aghecenco** [comment]
The last step of the `PATCH /drives` operation is to trigger a block device rescan. This rewrites the block device's config space and triggers a `VIRTIO_MMIO_INT_CONFIG` interrupt. After this, the API call returns. Meanwhile, the guest had to process the config change and update the device accordingly, but there's no way to communicate this from inside the guest back to Firecracker, so yes, it's possible that a `mount` attept *immediately* after the `PATCH` returns (successfully) can fail because the guest hasn't finished processing the config space change.

**Comment by xibz** [comment]
@aghecenco - Awesome, thank you for the clarification!
