### ISSUE TITLE
Check for Memory Leaks

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#119]
We have a bunch of unsafe code & usage of CString which needs to be deallocated explicitly.
We should check to see if we find any memory leaks. We could use valgrind. See https://creativcoder.github.io/post/checking_memory_leaks_in_rust_ffi/ as it might not work out of the box.

**Comment by memoryruins** [comment]
As of 1.28, the ``#[global_allocator]`` attribute [was stabilized](https://blog.rust-lang.org/2018/08/02/Rust-1.28.html), enabling the switch to the system or a custom allocator on a stable toolchain. Recently, nightly [switched the default allocator](https://github.com/rust-lang/rust/pull/55238#issuecomment-435609362) to ``System`` on all platforms.

**Comment by dianpopa** [comment]
Hi @memoryruins , This is really useful information that we were not aware of. Thank you!
Indeed, it seems that in the meantime there appeared some new additional datapoints from our last investigation that we could make use of:
* As per your information, `jemalloc` can now be replaced with the `System` allocator in the stable toolchain. We could try do that and give it a go with the `valgrind` tool. 
* As per #639, firecracker can be built with glibc also. This means that we should check again to see if the provided rustc sanitizers can now work with musl. If not, we could investigate with the glibc built binary and see what we find there.
For sure, this issue reached a state where it could use some fresh investigation and any help from community is greatly appreciated 👍 .

**Comment by AE1020** [comment]
An issue that arises is that Firecracker's main() does not return "cleanly".  [It's actually using `unsafe { libc::exit() }`](https://github.com/firecracker-microvm/firecracker/blob/ffbc2efcf2dcffa02db6df3474a8ad2b0bad21f7/src/vmm/src/lib.rs#L360)...which is more abrupt than Rust's `std::process::exit()` (which does some cleanup, but doesn't run destructors).

If one wants to return an integer exit status -and- guarantee all the destructors have run, the idiom is to put your main code in a wrapped function that returns an integer.  Then have the true main() call std::process::exit() with the result of the wrapper.  This way, all the code that could need destruction has finished.

**[I've done that, and tried to make some minimally invasive changes to get an `Option<ExitCode>` to bubble up for clean exit.](https://github.com/AE1020/firecracker/commit/df00f62876f0b134505ac7b5bbb611e17100c9e5)**

If speed of termination of the VMM is an issue...then clean shutdown could be optional, for sanitizer-oriented builds only.

But having a clean shutdown of this form is important, otherwise it's hard to tell if a "potential leak" is an "actual leak" or not.

**Comment by dianpopa** [comment]
Closing this in favor of #1662
