### ISSUE TITLE
Clarify build instructions and build requirements

### ISSUE THREAD

**Issue by montao** [firecracker-microvm/firecracker#1217]
The build instruction/requirement in the README is somewhat vague and maybe too broad.

_

> You can build Firecracker on any system that has Docker running

_

Looks like one needs at least Bash or a UNIX/Linux system because the build script uses Bash. I was able to build Firecracker using Ubuntu as host. But with Windows 10 Pro (and Docker installed) I don't know how to do it because the build script requires Bash. Maybe we can make it build from Windows 10 with Docker if we create a build script for it. I tried also using GitBash for Windows but got an error message there too.

**Comment by aghecenco** [comment]
Indeed, `bash` is a requirement for Windows too, but it's not enough. There's an error in the container invocation [here](https://github.com/firecracker-microvm/firecracker/blob/9945928e284ff760968ccc456de8bdd029216fc1/tools/devtool#L358):

https://github.com/firecracker-microvm/firecracker/blob/9945928e284ff760968ccc456de8bdd029216fc1/tools/devtool#L358

`/dev` can't be bind-mounted as-is on a Windows host because it's not there by default. I don't know at the moment if creating a placeholder would help; more deep dive is required to find out what the build container needs from `/dev` and if it can be made to work with replacements on Windows, or if we should update the build instructions, restricting them to unix systems.

**Comment by acatangiu** [comment]
@firecracker-microvm/compute-capsule what do you say we update the documentation to explicitly add `bash` and a `unix` OS as requirements?
