### ISSUE TITLE
EpollHandlerNotFound during PATCH /drives in v0.18.0

### ISSUE THREAD

**Issue by sipsma** [firecracker-microvm/firecracker#1272]
Hello, firecracker-containerd has begun working on the upgrade from Firecracker v0.17.0 to v0.18.0. The vsock-related updates have gone well so far, but there appears to be an unrelated regression related to patching drives after VM startup.

Whenever firecracker-containerd issues a PatchGuestDrive request, it now gets this error message: 
```
[PATCH /drives/{drive_id}][400] patchGuestDriveByIdBadRequest  &{FaultMessage:Error retrieving device epoll handler!}
```

I can see in the logs that the calls prior to this error that attach the drives were successful and it doesn't look like there were any drive-related API changes from 0.17->0.18, so I think we are still using the API correctly.

I'm not at all familiar with the Firecracker codebase so I easily may be misinterpreting this, but I did notice there was a test added between 0.17 and 0.18 that seems to actually assert that getting this error response is the expected behavior: https://github.com/firecracker-microvm/firecracker/blob/1e1cb6f8f8003e0bdce11d265f0feb23249a03f6/vmm/src/lib.rs#L2814-L2825

Was there any expected change in behavior related to patching drives between 0.17 and 0.18? If on the other hand this is suspected to be a bug, let me know if I can provide more information or try reproducing on different Firecracker commits to help track down the cause.

**Comment by dhrgit** [comment]
Patching a block device (i.e. a backing file change) should only fail during boot. More specifically, the short window between machine start and virtio-blk driver initialization. That's why the error is expected during that test (the vm state is artificially set to `Running`, while the device is not yet activated).

However, this behavior should be the same across both versions (0.17.0 and 0.18.0). @sipsma can you please post some more details on the specific use case that leads to this error. The steps to reproduce would be great.

**Comment by sipsma** [comment]
@dhrgit Thanks for the clarification, that makes much more sense. Based on your explanation, I tried adding an artificial 1 second sleep before the drive PATCH call to see if it was just happening too early in the boot cycle; it did indeed fix the issue and allowed the PATCH to complete successfully.

I'm now suspecting this is actually indirectly related to the vsock updates. I believe what's happening is:
1. We start the VM and then, from the host, try to connect to the Agent process we run inside the VM, which listens on a vsock port.
2. The first connect attempt fails because the VM is still booting and the Agent is not yet running/listening. This results (as the firecracker vsock docs state) in the socket getting closed after the host-side writes `CONNECT <port>`.
3. However, the code I wrote didn't check whether the socket was closed; it assumed after the successful write of `CONNECT <port>` that the socket was ready and passed it off to be used. This resulted in the connect "succeeding" much earlier than it should have and thus the PATCH drives to occur much earlier than it should have (resulting in the error we saw).

This is thus user error, but I do have a follow-up question. Do you have any recommendation on ways to check that the socket was not closed after writing `CONNECT <port>`? Ways I can think of:
1. Have the host-side socket attempt to write something after `CONNECT <port>`, i.e. write `HELLO\n`, which should only succeed if the socket is not closed. Then have the VM guest-side socket be sure to read that message before passing the socket off to be used by anything else (so there aren't unexpected stray bytes sitting on the socket).
1. I tried doing a zero-byte write to the socket from the host-side, but that appears to succeed even if the socket was not actually connected successfully (I can't find any definitive docs on what the expected behavior is for zero-byte writes to closed sockets, so maybe it's undefined?)

I suspect 1. above works, but it does seem to introduce a fair bit of extra complication and more error cases to handle, so I want to make sure there's not an obviously better way of handling this that I'm missing.

**Comment by dhrgit** [comment]
I think it makes sense to treat the vsock connect procedure as an async connect (i.e. one where you need to subsequently check the operation status). When connecting from the host to a guest listener which may not yet be there, I suggest having the listener ack the connection via some sort of message, such as the hello you mentioned, but sent from guest to host (i.e. `HELLO host-client`); like a server sending its banner as a greeting. This way, on the host side, after writing `CONNECT <port>`, you can try to read from the socket (or poll it for reading) and:
- if the read is 0-sized, retry, since that means the connect call has failed (the host-side Unix socket connection has been closed);
- if the read yields the ack message (banner, hello, w/e), it means the connection has been established, and therefore the guest has booted up and reached userspace init.

**Comment by sipsma** [comment]
@dhrgit Makes sense, will give that a try and open a separate issue if I run into anything else. Closing this one, thanks for your help!
