### ISSUE TITLE
Documentation on the GitHub page reflects HEAD and not the latest release

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1289]
As we add/remove/change behavior and make doc changes, the documentation reflects the committed code, but not the released code.

We've seen multiple occurrences of users trying to unsuccessfully configure/use the latest released `firecracker` binary following documentation which is no longer applicable.

Options to keep binary and docs in sync:

1. Have separate branches `release` and `devel`, with `release` being the main branch that gets displayed in the GitHub repo, and only update `release` when we do a release and publish a new binary.
2. Release documentation along with the binaries and guide users to checking the docs from the release page.
3. ???

**Comment by acatangiu** [comment]
Tracking issues that have this root-cause: #1128

**Comment by acatangiu** [comment]
Tracking issues that have this root-cause: #1288

**Comment by andreeaflorescu** [comment]
**Proposal 1**: The problem is that the branch that gets displayed in the GitHub repository is also the branch on which PRs are automatically created. For this reason I don't think that this is a good idea at the moment.
I researched a bit and it looks like GitHub does not support something like one default display branch and one default branch against which to create PRs. You can of course change the branch against which you create a PR on the PR page, but only before you click on "Create Pull Request". This has the potential to be prone to errors.

**Proposal 2**: I like this one.

**Comment by dianpopa** [comment]
Given that we now have a branch for each release, we are no longer affected by this problem.
