### ISSUE TITLE
Vsock documentation has wrong endpoint

### ISSUE THREAD

**Issue by cpheps** [firecracker-microvm/firecracker#1290]
Looks as though the documentation for the vsock endpoint is wrong in both the [docs/vsock.md](https://github.com/firecracker-microvm/firecracker/blob/master/docs/vsock.md) and in the [OpenAPI docs](https://github.com/firecracker-microvm/firecracker/blob/master/api_server/swagger/firecracker.yaml#L356). 

From testing it seem like the endpoint should be a `PUT` to `/vsocks/{ID}` rather than `/vsock`

**Comment by acatangiu** [comment]
Hi @cpheps, as can be seen in the CHANGELOG, the change in API has not been yet released. It will be included in our next v0.19.0 release.

You can use it with `/vsock` if you build the binary yourself from the HEAD of the master branch, if you're using the **released** v0.18.0 binary, please `git checkout v0.18.0` the repo so that the docs are in sync with the binary.

We're tracking this type of confusion in #1289.

**Comment by cpheps** [comment]
Cool thanks for following up I'll close this issue then.
