### ISSUE TITLE
MMDS not available when API server is disabled

### ISSUE THREAD

**Issue by lauralt** [firecracker-microvm/firecracker#1292]
At this moment, MMDS is not available when we disable API thread by passing `no-api` parameter to Firecracker. We should be able to configure also MMDS in the file that is used for the configuration of microvm.

**Comment by sandreim** [comment]
I think it would make sense to have the MMDS config as a separate file since it might be quite big and it makes sense to be decoupled from the actual VM configuration.

**Comment by tsk9** [comment]
Does anyone know why PR #1367 was closed without comment? I like to see the feature implemented to be able to use files for both config and metadata to avoid the interaction with the API server.

**Comment by serban300** [comment]
Hi @tsk9 ! I'm not sure why the PR was closed, but your use case definitely makes sense. I see the PR can't be reopened, but we'll create a new one.

**Comment by georgepisaltu** [comment]
Hi @tsk9 ! I have opened a new PR and will try to gather feedback on this one while I work on it. Let me know if it fits your use case.

https://github.com/firecracker-microvm/firecracker/pull/2145

**Comment by tsk9** [comment]
Hello @georgepisaltu, thanks for creating the PR #2145. This will perfectly match my use case loading both config and metadata from JSON files. I guess that the mmds listen address is not configurable? No issue in my case, because it will default to `169.254.169.254` which is what `cloud-init` expects.

**Comment by richardcase** [comment]
+1 on this feature for me.

We'd want to use this feature as it would allow us to use cloud-init with the api disabled. So set `meta-data` and `user-data` items in mmds.

**Comment by richardcase** [comment]
@georgepisaltu - are there any plans to carry on working on this?

**Comment by richardcase** [comment]
@georgepisaltu -  continuing the chat on the PR and taking into consideration the comments on this issue if i was to work on this issue i'd probably do the following:

1. Add a new flag like you did so that you can specify mmds content via a file (`--metadata` or `--mmds-content`). The file structure being something like this:
```json
{
    "latest": {
        "meta-data": "BASE64ENCODED==",
        "user-data": "BASE64ENCODED=="
    },
    "2016-09-02": {
        "meta-data": "BASE64ENCODED=="
    } 
}
```
The contents of the metadata items will be base64 encoded in the file.
2. Add a `MmdsContent` struct [here](https://github.com/firecracker-microvm/firecracker/blob/24cc8d9b689d31de95ae33eca16273383f01b79e/src/vmm/src/vmm_config/mmds.rs) to represent the mmds content in 1) and use that to represent the mmds content.
3. I'd also test the UX around adding in directly to the [VmmConfig](https://github.com/firecracker-microvm/firecracker/blob/0690010524001b606f67c1a65c67f3c27883183f/src/vmm/src/resources.rs#L52) to see how it felt using the same `--config-file` argument instead of a separate flag (just to see which works best for useability).
4. Add validation to ensure that that its not possible to use the same keys (and other failure scenarios). So, these 2 scenarios shouldn't be possible:
```json
{
    "latest": {
        "meta-data": "BASE64ENCODED==",
        "meta-data": "BASE64ENCODED=="
    } 
}
```
And
```json
{
    "latest": {
        "meta-data": "BASE64ENCODED==",
    },
    "latest": {
        "meta-data": "BASE64ENCODED=="
    } 
}
```
5. Add integration tests to cover the new feature (happy path and also negative tests)

**Comment by georgepisaltu** [comment]
Regarding 1), I don't see the need to enforce the base64 encoding on MMDS contents. I think with a more general approach, like the one in the original PR where we had no encoding, would fit best while also allowing users such as yourself to customize it however they see fit. You could easily create the metadata file with whatever encoding or encryption you want, then also do the decoding/decryption logic in the guest.

In essence, this feature is supposed to act exactly like a PUT on /mmds at VM startup. This is achieved by calling [`MMDS.put_data()`](https://github.com/firecracker-microvm/firecracker/blob/main/src/mmds/src/data_store.rs#L73), which is also [called through the API server on PUTs on /mmds](https://github.com/firecracker-microvm/firecracker/blob/main/src/api_server/src/lib.rs#L345). This also means that you don't need a separate container for the MMDS content as you can just plug it in the MMDS struct directly, which eliminates the need for 2). As for parsing the file and converting it into a JSON object, you can follow the method used in the [API server parsing](https://github.com/firecracker-microvm/firecracker/blob/main/src/api_server/src/request/mmds.rs#L15). `serde_json` offers great tools here and already deals with the error cases mentioned at 4).

3) and 5) sound reasonable to me and I'll be happy to review your PR when you're ready. Thank you for picking this up!

**Comment by richardcase** [comment]
Great feedback, thanks @georgepisaltu  :+1:  I will get working on the change.

**Comment by richardcase** [comment]
@georgepisaltu  - a question on 4). The behaviour of `serde_json` is to take the last value if there are duplicate keys. So if we have (which is a contrived sample):
 ```json
{
    "latest": {
        "meta-data": "value1",
    },
    "latest": {
        "meta-data": "value2"
    } 
}
```
there won't be an error from `serde_json` and the following will be added to mmds:

```json
{
    "latest": {
        "meta-data": "value2"
    } 
}
```

Do you think we should catch this? It feels like we should return an error to the user but i'm undecided. We can use `serde_with::rust::maps_duplicate_key_is_error` if we decide to add it.
