### ISSUE TITLE
rustfmt is not available for aarch64 with Rust 1.38

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1322]
Once we update to Rust 1.38, we will not be able to run fmt in the CI because it isn't available. A temporary workaround is to only run rustfmt on x86_64.

**Comment by dianpopa** [comment]
For Firecracker's case where we will always run the CI on x86_64 too, this should not be a issue since rustfmt will also format the aarch64 specific code. So, it should be enough to run rustfmt on x86_64 no matter what. Once we make the `test_rust_style` test from the CI x86_64 specific, this issue could be closed.

**Comment by andreeaflorescu** [comment]
In the PR where we move to rust 1.38 rustfmt is run only on x86_64, but maybe I should update the reason why we are skipping it on aarch64.
