### ISSUE TITLE
Decouple Vmm code into controller/builder and live-vmm

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1427]

**Comment by dianpopa** [comment]
With a Vmm controller/builder in place, the road to freeing the seccomp filter of the `timerfd_create` syscall seems a lot simpler  since the Vmm Builder could simply just allocate the needed timerfds before starting the microVm. If we aim for a more forward looking solution we could try implementing a resource pooling approach like the one displayed in #1281.
