### ISSUE TITLE
Ratelimiter: Very high CPU usage when ratelimiter is throttling guest RX.

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#1439]
When rate limiting is enabled and the guest is receiving a lot of traffic that triggers throttling the emulation thread will use 100% CPU.

There are 2 possible approaches here:
- quick fix: keep the current code structure and configure edge triggered epoll for the tap fd.
- proper fix: rework the current state machine and use edge triggered epoll

**Comment by pyrito** [comment]
Hi @sandreim could you give some more context to this problem?

**Comment by sandreim** [comment]
Hi @pyrito,

The issue happens when the net device does not read all the the packets from the TAP device waiting for the limiter to replenish it's budget. When that happens the epoll loop will continuously fire the RX_TAP_EVENT until all packets will be received. There is already some code that unregisters the epoll event when there are no more free RX buffers but that does not cover the case when we stop processing the tap RX due to limiter budget.

**Comment by pyrito** [comment]
Hi @sandreim , I think @mi-yu and I can help take a stab at this problem.

**Comment by pyrito** [comment]
@sandreim 

I was wondering if you could explain what you meant by two of your suggested fixes?

- "configure edge triggered epoll for the tap fd", we looked through the code and found the part of the code that does not unregister the epoll event when the tap RX is being blocked due to reaching its budget. Could you clarify what you meant by configuring the edge triggered epoll?

- "rework the current state machine and use edge triggered epoll" could you give some general context towards how to make this "proper" fix.

Thank you for your time!

**Comment by andreeaflorescu** [comment]
Hey @pyrito. @sandreim already has a fix for this and he will probably post it early next week. Do you need help in finding another issue?

**Comment by pyrito** [comment]
@andreeaflorescu , yes that would be greatly appreciated! If there are any issues of easy difficulty that we could tackle that would be much appreciated. Thanks!
