### ISSUE TITLE
GNU-GCC build fails to boot MicroVM

### ISSUE THREAD

**Issue by rbrasga** [firecracker-microvm/firecracker#1515]
I have the build using the 'musl' compiler working. But the build using the 'gnu' compiler will not work. I have verified on tag v0.20.0.

#In One Shell:
./tools/devtool build -l gnu
rm -f /tmp/firecracker.socket
./firecracker --api-sock /tmp/firecracker.socket
#Run the commands in the 2nd shell
#MicroVM Fails to Boot with this error:
2020-01-16T13:55:07.572561421 [anonymous-instance:ERROR:src/vmm/src/signal_handler.rs:37] Shutting down VM after intercepting a bad syscall (39)

#In Another Shell:
#Follow everything in the Getting Started Guide: https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md
#'musl' works following these steps, 'gnu' does not.

--

Am I missing something simple? Do the kernel and rootfs need to be tied together with 'gnu' to run on a 'gnu' build?

Looking forward to your response.

**Comment by petreeftime** [comment]
It fails to start due to seccomp filtering. The allowed syscalls are validated only for musl and since GNU might use different syscalls to do the same thing, sometimes you can get an error like this. One way to deal with it is to update the seccomp filter list and there's some ongoing work to allow users to do that more easily (https://github.com/firecracker-microvm/firecracker/pull/1431), but you can also disable syscall filtering by passing: `--seccomp-level 0` when running firecracker, if you're running a VM that you trust.

**Comment by rbrasga** [comment]
Thank you, that resolved my issue. Would it be possible to document this in a wiki if it wasn't yet?

Feel free to close the issue.

**Comment by andreeaflorescu** [comment]
@rbrasga thanks! I created an issue for taking care  of your suggestion. Thanks!
