### ISSUE TITLE
Avoid wrapping Vmm in an Arc<Mutex>

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1553]
With PR #1550 the `Vmm` object is wrapped in an Arc<Mutex> as it needs to implement the `EpollHandler` trait for the exit event.

We can change this in a future PR by either deciding on dropping Arc for all implementors of EpollHandler or just lock parts of the Vmm in an Arc which are actually needed for handling the read event.

**Comment by acatangiu** [comment]
I'm not sure there exists a good path forward here.

> either deciding on dropping Arc for all implementors of EpollHandler

The current available Firecracker `EventManager` implementation as well as the proposed https://github.com/rust-vmm/vmm-epoll/pull/2 implementation, both enforce `Arc<Mutex>` wrapping of event handlers.

> or just lock parts of the Vmm in an Arc which are actually needed for handling the read event

That would mean splitting off parts of the `Vmm` to another struct which will be `Arc<Mutex>` wrapped inside the `Vmm` struct. These parts would be: `exit_event` and all other members accessed on the `exit_event` path: `vcpus_handles`, `vmm.stop() function` and all `self` members accessed within.

That would not avoid the `Mutex` lock, just move it inside Vmm, and I think it would artificially raise the complexity of `Vmm`.

I suggest we stay with the current design, especially since the Mutex wrapping the Vmm is un-contended.

Ideally, in the future we'd have an `EventManager` capable of managing both single-threaded and multi-threaded subscribers at the same time. That would provide a clean solution to this issue.

In the meantime I suggest closing this issue. @andreeaflorescu what do you think?

**Comment by andreeaflorescu** [comment]
Sure, we can close this issue.

**Comment by acatangiu** [comment]
Closing for now, we can reopen when we have support in a more flexible `EventManager`.
