### ISSUE TITLE
Jailer in master seems to fail our test suite

### ISSUE THREAD

**Issue by xibz** [firecracker-microvm/firecracker#1557]
We have set up a new test pipeline that builds and tests against HEAD of firecracker. The reason we decided to do this is to catch issues earlier, like the removal of `seccomp-level` from the jailer. We have since fixed that, but ran into another issue that is really obscure.

```
2020-01-28T23:20:50.453824122 [anonymous-instance:ERROR:src/firecracker/src/main.rs:66] Firecracker panicked at 'Error creating the HTTP server: IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
2020-01-28T23:20:50.454184795 [anonymous-instance:ERROR:src/firecracker/src/main.rs:76] stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
```

https://github.com/firecracker-microvm/firecracker-go-sdk/pull/176

**Comment by kzys** [comment]
Is it #1548?

**Comment by xibz** [comment]
@kzys - Yea, that looks like to be the issue. Will go ahead and close. Thanks!

**Comment by KarthikNedunchezhiyan** [comment]
@xibz if possible try to pass _**--api-sock /api.socket**_ after -- in jailer. if this solved the issue we can confirm it is similar to #1548 .

**Comment by lauralt** [comment]
@xibz #1548 should indeed be the issue, as @KarthikNedunchezhiyan said, you can check this by passing `-- --api-sock /some_random_name` and let us know if it still fails. The problem here is that, when running jailer only with the required parameters (without `--api-sock` extra arg), Firecracker will try to create the socket at `/run/firecracker.socket` default location, but fail because it doesn't have ownership to automatically create a directory hierarchy and have the proper permissions. For example, the same issue would appear if you pass `-- --api-sock /some/path/to/a/file`. A workaround here would be to manually create a `run` dir in jailer's root and change its ownership with the desired uid and gid. Anyway, this should be fixed when #1548 gets merged.

**Comment by dianpopa** [comment]
Yes, this is #1548. Will try to merge asap.

**Comment by dianpopa** [comment]
Fix #1548 was merged. Please let us know if problem is solved for you. Thanks!

**Comment by xibz** [comment]
Did you guys move the location of the socket under `/run`? Is that intentional?

**Comment by KarthikNedunchezhiyan** [comment]
> Did you guys move the location of the socket under /run/firecracker.socket? Is that intentional?

@xibz yes it is intentional. firecracker socket location has been moved from _**/tmp/firecracker.socket**_  (_**/api.socket**_ if launched using jailer) to _**/run/firecracker.socket**_

> Or is that something else? Some more context, previously we did not specify the api-sock flag and relied on the default behavior of the socket being placed in the root directory. Has that now changed?

Yes, From next firecracker version user has to pass `--api-sock` to override default socket location. If `--api-sock` not passed it will use default location (_**/run/firecracker.socket**_).

We have mentioned this in [CHANGELOG.md](../blob/master/CHANGELOG.md).

**Comment by xibz** [comment]
@KarthikNedunchezhiyan - Okay, thank you. Just wanted to make sure that this was an intentional change. Closing as this has been resolved.

Thanks!
