### ISSUE TITLE
Add tests for vmm::controller.rs

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1623]

**Comment by iulianbarbu** [comment]
Closed due the fact we do not need to test any unit from here, since they are covered by the integration tests:


* `pub fn flush_metrics(&mut self) -> ActionResult` covered by `integration_tests/functional/test_logging::test_flush_metrics`.
* `pub fn send_ctrl_alt_del(&mut self) -> ActionResult` covered by `integration_tests/functional/test_api::test_send_ctrl_alt_del`.
* `pub fn rescan_block_device(&mut self, drive_id: &str) -> ActionResult` covered by `integration_tests/functional/test_rescan_file` and `integration_tests/functional/test_drives::test_rescan_dev`.
* `fn update_drive_disk_image(
        &mut self,
        drive_id: &str,
        disk_image: File,
    ) -> result::Result<(), DriveError>` covered by `integration_tests/functional/test_drives::test_partuuid_update`.
* `pub fn update_block_device_path(
        &mut self,
        drive_id: String,
        path_on_host: String,
    ) -> ActionResult` covered by `integration_tests/functional/test_drives::test_patch_drive`
* `pub fn update_net_rate_limiters(
        &mut self,
        new_cfg: NetworkInterfaceUpdateConfig,
    ) -> ActionResult` covered by `integration_tests/functional/test_rate_limiters::test_(rx|tx)_rate_limiting`.
