### ISSUE TITLE
Lots of print out of "RX queue is empty"

### ISSUE THREAD

**Issue by photoszzt** [firecracker-microvm/firecracker#1677]
I'm seeing lots of print out in VM with the following text:

anonymous-instance:ERROR:src/devices/src/virtio/net/device.rs:546] The RX queue is empty, there is no available buffer.

The exact case might be hard to reproduce. I'm running GPU virtualization using https://github.com/utcs-scea/ava with TensorFlow inference workload. The GPU virtualization software is forwarding apis which creates lots of network traffic. The guest os is Linux.

**Comment by iulianbarbu** [comment]
Hi, @photoszzt ,

This is a log which I've introduced in [Drive net device with polly PR](https://github.com/firecracker-microvm/firecracker/pull/1518/commits/6aa68d5b84fb72fb57dd0ac621b4a846dd024ab8#diff-640134827a9fab72994cb080c1686fefR561). Before this change, instead of logging an error for `NoAvailBuffer`, we were throwing an error, which was not handled by any means, so it was a noop catch for it. If I am not mistaken, I think that the log is not really necessary, or at least it shouldn't be considered an error. As far as I understand, the reason behind this log is that the network device RX queue does not have any available descriptors for incoming data, when the event for incoming data happens. This can happen, as you said, for heavy network traffic applications. If I am not wrong, this can be done with an one line fix, in which we remove the line with the log. @firecracker-microvm/compute-capsule , WDYT?

**Comment by raduiliescu** [comment]
Other option would be to implement log ratelimit functionality as in linux kernel - https://elixir.bootlin.com/linux/v4.0/source/include/linux/ratelimit.h#L48.

**Comment by raduiliescu** [comment]
Also this sounds more like a condition where a metric is enough, we don't need a log.

**Comment by acatangiu** [comment]
> If I am not wrong, this can be done with an one line fix, in which we remove the line with the log. @firecracker-microvm/compute-capsule , WDYT?

Yes, and also check all other events on all devices for similar log messages, logging is slow and shouldn't happen on hotpaths like this. Like @raduiliescu said, metrics are enough for such cases.

> Other option would be to implement log ratelimit functionality as in linux kernel - https://elixir.bootlin.com/linux/v4.0/source/include/linux/ratelimit.h#L48.

Would be great to add this to our logger (not part of this issue though).
