### ISSUE TITLE
Avoid cloning MacAddr on each network packet TX

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1712]
'MacAddr' is Copy so each call to 'write_to_mmds_or_tap()' would create a copy of the underlying buffer.
References could be used instead to avoid the copy.

**Comment by andreeaflorescu** [comment]
`MacAddr` is just 6 bytes and should qualify as a small structure. For small structures copy vs reference becomes a discussion on code readability rather than performance. In some synthetic benchmarks pass-by-copy outperforms pass-by-reference. When you use a reference, you use 8 bytes irrespective of the size of the structure, and since this one only has 6 bytes, copy is actually saving more space. I don't think this change is necessary.

Benchmarks available here: https://www.forrestthewoods.com/blog/should-small-rust-structs-be-passed-by-copy-or-by-borrow/

**Comment by acatangiu** [comment]
That's true, `Option<MacAddr>` is smaller in size than a reference so it's definitely faster to send it by value than by reference (we also avoid dereferencing).

Good catch, closing this issue!
