### ISSUE TITLE
Feature request: Track kernel 4.14, 4.19 & 5.4 config (separately?)

### ISSUE THREAD

**Issue by bbros-dev** [firecracker-microvm/firecracker#1724]
Currently, there is no documented example that "Just Works", including build of kernel and rootfs images from sources.  I'm aware of the firecracker-demo that delivers compiled kernel and rootfs  images. 

After downloading `resources/microvm-kernel-config` to `~/usr/src/linux-source-4.19/.config`

Debian stable `make -C linux-source-$KERNEL_SOURCE_VERSION silentoldconfig` halts any build script at:

- `Build ID Salt (BUILD_SALT) [] (NEW)` (Set to some full kernel version (e.g. 4.19.98-1) to ensure reproducible builds?)
- `CPU isolation (CPU_ISOLATION) [Y/n/?] (NEW)`
- TSX enable mode
```bash
TSX enable mode
> 1. off (X86_INTEL_TSX_MODE_OFF) (NEW)
  2. on (X86_INTEL_TSX_MODE_ON) (NEW)
  3. auto (X86_INTEL_TSX_MODE_AUTO) (NEW)
choice[1-3?]:
```
- `Stack Protector buffer overflow detection (STACKPROTECTOR) [Y/n/?] (NEW)`
- `Strong Stack Protector (STACKPROTECTOR_STRONG) [Y/n/?] (NEW)`
- `Enable support for latency based cgroup IO protection (BLK_CGROUP_IOLATENCY) [N/y/?] (NEW)`
- `Enable infrastructure for get_user_pages_fast() benchmarking (GUP_BENCHMARK) [N/y/?] (NEW)`
- `Transformation virtual interface (XFRM_INTERFACE) [N/m/y/?] (NEW)`
- `XDP sockets (XDP_SOCKETS) [N/y/?] (NEW)`
- `Netfilter OSF over NFNETLINK interface (NETFILTER_NETLINK_OSF) [N/m/y/?] (NEW)`

+ seventy-eight (78) additional choices.

**Comment by bbros-dev** [comment]
Alternatively, could a Firecracker admin up-vote this [weaveworks feature request](https://github.com/weaveworks/ignite/issues/568) to break out their `images\kernel\` to a separate project and then link to that in the Firecracker documentation?

**Comment by bbros-dev** [comment]
In the interim, interested users can track [Weaveworks/Ignite](https://github.com/weaveworks/ignite) kernels here:

[BegleyBrothers/firecracker-kernels](https://github.com/BegleyBrothers/firecracker-kernels)

### AMD64

- [Kernel config-amd64-4.14.166](https://github.com/BegleyBrothers/firecracker-kernels/blob/master/weaveworks/images/kernel/versioned/config-amd64-4.14.166)
- [Kernel config-amd64-4.19.97](https://github.com/BegleyBrothers/firecracker-kernels/blob/master/weaveworks/images/kernel/versioned/config-amd64-4.19.97)
- [Kernel config-amd64-5.4.13](https://github.com/BegleyBrothers/firecracker-kernels/blob/master/weaveworks/images/kernel/versioned/config-amd64-5.4.13)

### ARM64

- [Kernel config-arm64-4.14.166](https://github.com/BegleyBrothers/firecracker-kernels/blob/master/weaveworks/images/kernel/versioned/config-arm64-4.14.166)
- [Kernel config-arm64-4.19.97](https://github.com/BegleyBrothers/firecracker-kernels/blob/master/weaveworks/images/kernel/versioned/config-arm64-4.19.97)
- [Kernel config-arm64-5.4.13](https://github.com/BegleyBrothers/firecracker-kernels/blob/master/weaveworks/images/kernel/versioned/config-arm64-5.4.13)

**Comment by iulianbarbu** [comment]
Hey, @bbros-dev ! 

> Debian stable make -C linux-source-$KERNEL_SOURCE_VERSION silentoldconfig halts any build script at:

Is this issue referring in the first place to the fact that when you build the 4.19 kernel with the `microvm-kernel-config` you are asked about all those additional choices? I noticed this once, when I've tried to compile a 4.19 kernel, and it's happening most probably because the `microvm-kernel-config` is a 4.14 kernel generated config, while 4.19 has new additional features which are not contained by the config. I think the right and clean thing to do in this case is to open a PR against master with kernel configs proposals for 4.19 and 5.4. This would need regenerating the kernel configs for these kernel versions. I can open the PR.

> Alternatively, could a Firecracker admin up-vote this weaveworks feature request to break out their images\kernel\ to a separate project and then link to that in the Firecracker documentation?

I understand that you suggest to link our kernel configs to a separate resource from an external project. This does not feel very right to me. Linking resources from projects outside firecracker-microvm org would require keeping an eye on those projects. Furthermore, it implies that we are not the owners of the projects, and any changes would require approval from someone else, which might or might not be given. I think it would add unnecessary complexity, at the moment.

Quoted from  [weaveworks feature request](https://github.com/weaveworks/ignite/issues/568):

> 3. PR to Firecracker-Demo to add the weaveworks/firecracker-kernels project to the README.md

Besides the `linking external resources inside our repos` issue, I think that this action item is not suited for `firecracker-demo` repository. This repository was created to pin point an example of how Firecracker can be used at scale. The resources from this repository are suited for users which want to use existing scripts to create the necessary underlying configuration that makes possible spawning multiple Firecracker microVMs.  In my opinion `firecracker-demo` is not really a how to customize and run Firecracker microVMs guide.

**Comment by bbros-dev** [comment]
> I think the right and clean thing to do in this case is to open a PR against master with kernel configs proposals for 4.19 and 5.4.

OK.

> This would need regenerating the kernel configs for these kernel versions.

Actually I now understand this is already done within weaveworks/ignite.

I've setup a project mirroring that subset of the weaveworks/ignite code base related to kernel building: [BegleyBrothers/firecracker-kernels](https://github.com/BegleyBrothers/firecracker-kernels)
This seems more sophisticated and complete than anything else currently available.

I think the rootfs building code base is categorically distinct from (but relevant to) kernel builds - so we may track that as a separate `firecracker-rootfs` repository.

> I understand that you suggest to link our kernel configs to a separate resource from an external project. This does not feel very right to me.

OK.

> ..any changes would require approval from someone else

No that wouldn't be the case.  My understanding is this reason is why git was designed with forking as the relation between projects.  

So you can now fork [BegleyBrothers/firecracker-kernels](https://github.com/BegleyBrothers/firecracker-kernels) and be in full control of your own destiny.  
Remove the file `weaveworks/.subrepo` and you're further isolated from upstream.

**Comment by aghecenco** [comment]
Jumping in with my 2 cents:

> >  I think the right and clean thing to do in this case is to open a PR against master with kernel configs proposals for 4.19 and 5.4.

> OK.

I thought a bit about the added kernel configs and I think that they are not a mandatory resource to include in the Firecracker repo. Ideally, Firecracker users would build specialized kernels, optimized for their various workloads. The configs currently present in the Firecracker repo are for demonstrative purposes; the direction we recommend is adding improved documentation and recipes for building customized kernels (and other resources) for Firecracker microVMs. I'll reiterate this thought on #1727.

> I think the rootfs building code base is categorically distinct from (but relevant to) kernel builds

Sounds reasonable. There are several related opened issues and a PR attempt: #1676, #1048 , #1418.

> so we may track that as a separate firecracker-rootfs repository.

I don't think there's need to create a standalone repo for that. Once the guides and tooling become available in Firecracker, they should be a solid enough starting point for users to extend and customize.

>  No that wouldn't be the case. My understanding is this reason is why git was designed with forking as the relation between projects.

> So you can now fork BegleyBrothers/firecracker-kernels and be in full control of your own destiny.
Remove the file weaveworks/.subrepo and you're further isolated from upstream.

The issue here is not the mechanics of including configs in the Firecracker repo, but whether having a collection of pre-made configs (likely to grow organically in time) is the right thing to do long term. To reiterate, I don't think it is. Just as Firecracker is a building block in complex virtualization ecosystems, the examples and guides included in the repo should also be just that - starting points for customized environments.

**Comment by bbros-dev** [comment]
> I thought a bit about the added kernel configs and I think that they are not a mandatory resource to include in the Firecracker repo.

OK. Will be good to have some clarity.  I agree this is likely not the best use of firecracker developer cycles right now.

>  the direction we recommend is adding improved documentation and recipes for building customized kernels (and other resources) for Firecracker microVMs.

Also good to know.  However as you can see by the number of issues and around incomplete documentation - not pointing to working instructions creates a time sink for the project.  
The current instructions are, in my experience and observation, a source of drag, and will be non-trivial to update.

Removing [the current incomplete instructions](https://github.com/firecracker-microvm/firecracker/blob/master/docs/rootfs-and-kernel-setup.md) and replace them with pointers to the Weaveworks Ignite [kernel](https://github.com/weaveworks/ignite/blob/master/images/kernel) and [rootfs](https://github.com/weaveworks/ignite/blob/master/images) areas is a trivial change that stops [new users](https://github.com/firecracker-microvm/firecracker/issues/1048#issuecomment-480850783) getting the wrong idea about the state of instructions.

Suggestion:

```markdown
Building working kernel and rootfs combinations for a particular distribution is a 
non-trivial exercise.  
Until we have complete working documentation we suggest you review and use as
your starting point the the code and documentation in the Weaveworks Ignite project.

Kernel build details are 
[under `images/kernel`](https://github.com/weaveworks/ignite/tree/master/images/kernel).

RootFS build details for a distributions are 
[under `images/<distribution>`](https://github.com/weaveworks/ignite/tree/master/images/).

For a working `initrd` example 
[we suggest](https://github.com/firecracker-microvm/firecracker/issues/1418#issuecomment-575179780) 
you start by 
[reviewing the project `marcov/firecracker-initrd`](https://github.com/marcov/firecracker-initrd).
```
 
> but whether having a collection of pre-made configs (likely to grow organically in time) is the right thing to do long term. To reiterate, I don't think it is.

Agreed.  Experience proves that such details become a [separate project](https://github.com/jedi4ever/veewee/tree/master/templates).
However, having known-to-work kernel configuration for each of the LTS kernels is not too much expect - my working assumption (hope) is you're testing against these three kernels? So just make those test kernel configs public.  
Three LTS kernel configs seem not too much to maintain for this sort of project, and since they're your test bed (I'm assuming) are being maintained already?

**Comment by bbros-dev** [comment]
We're closing this simply because we won't be able to spend any more time on this.

For us this issue is resolved by knowledge of  [Weaveworks/Ignite](https://github.com/weaveworks/ignite) kernel and rootfs build documentation and working code.

For initrd knowing about the project [`marcov/firecracker-initrd`](https://github.com/marcov/firecracker-initrd) resolves this issue wrt to initrd builds.

We're working on [BegleyBrothers/firecracker-kernels](https://github.com/BegleyBrothers/firecracker-kernels) and hoping to push anything substantial upstream to [Weaveworks/Ignite](https://github.com/weaveworks/ignite).
