### ISSUE TITLE
move `MacAddr` from dumbo to utils

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#1765]
`MacAddr` is a simple wrapper and a utility used by multiple crates. Right now this is in `dumbo` and `dumbo` is used in a dependency in the following crates:
- vmm for `MacAddr`
- devices for `MacAddr` and for the MMDS network stack
- utils for `MacAddr`

By moving `MacAddr` to `utils`, we make `utils` a tinier crate. We can also push this code to rust-vmm/vmm-sy-util.

**Comment by iulianbarbu** [comment]
With the corresponding changes, `vmm` will not depend anymore on `dumbo`. 

However, `devices` and `utils` will still depend on `dumbo`. 

To me personally, I do not find appropriately to have a `device` dependent on a `network stack` (in our case `Net` device depends on `dumbo::ns`) because of the real world hierarchy (software sits on top of hardware) . I would prefer it the other way around. However, in our case, I do not know for sure if it would work the same, worse, or not at all. If it will work the same, we get rid of the dependency of `devices` on `dumbo`.

In terms of `utils` dependency on `dumbo`, I find it unnecessary. `dumbo` is used in `utils` to unit test the `Tap`, as in sending IPv4 packets and ARP frames on the tap, and verifying at the other end if the packet/frames retrieval is successful (not verifying if they are the same). This leads me to the conclusion that it is just enough to send some plain data on the tap, and receive it back with success, and keep the same behavior for the tap unit tests, and for the `Tap` implementation as well. We can remove the dependency on `dumbo` by modifying the current tap unit tests.

IMO, there are still issues with dependency "compliance", in terms of `dumbo`, because it has a dependency on `mmds` crate. The reason is that the specific mmds network stack implementation (`dumbo::ns`) which resides in `dumbo` works very closely with `mmds`, which can not be avoided. To resolve this issue, we can move the specific mmds network stack implementation to `mmds`, and make also generic some bits of code from dumbo's `tcp::handler`, which depends on a method from `mmds`. Now, I think `dumbo`  will be a really self contained crate.

@firecracker-microvm/compute-capsule , WDYT?

**Comment by andreeaflorescu** [comment]
@iulianbarbu this is a sane separation of concerns. Do you want to create issues to describe what needs to be done? Your issue explains it pretty well already.

**Comment by iulianbarbu** [comment]
> @iulianbarbu this is a sane separation of concerns. Do you want to create issues to describe what needs to be done? Your issue explains it pretty well already.

I will open separate issues for each mentioned crate.

**Comment by jmcconnell26** [comment]
I had an attempt at this as a first issue here.
https://github.com/firecracker-microvm/firecracker/pull/2083
@iulianbarbu, if the issues you mention above are still open, I would be interested to have an attempt at them.
