### ISSUE TITLE
Use TempFile from vmm-sys-util to cleanup test files

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#1803]
The vast majority of tests cleanup after themselves using `TempFile`, but there are some cases where `TempFile` cannot be used (like the Vsock UDS or the API UDS).

For these cases, a `TempPath` object can be used to cleanup whatever is at inner path when object goes out of scope.

Grepping for `fs::remove_file` in Firecracker shows many places where this is manually done over and over.

**Comment by acatangiu** [comment]
This can be done without adding new `TempPath` in `vmm-sys-util` like so:

```rust
let mut temp_uds_path = TempFile::new().unwrap();
// Remove the file so the path can be used by the socket.
temp_uds_path.remove().unwrap();

// Crate sock at `temp_uds_path.as_path()`.
// It will be deleted when `temp_uds_path` goes out of scope.
...
```

**Comment by acatangiu** [comment]
Not completely done yet.

For example:

-  `src/api_server/src/lib.rs::test_bind_and_run()`
- `src/vmm/src/vmm_config/vsock.rs::TempSockFile` - this can be reworked to the same simple model.

**Comment by acatangiu** [comment]
Hi @shioyama18, I've reopened this as your PR didn't address all occurrences where we can apply this model. Let us know if you want to continue with these improvements.

**Comment by shioyama18** [comment]
Hi @acatangiu , I would like to keep working on this issue, but I have two questions:
1. Should I update doc tests too? (https://github.com/firecracker-microvm/firecracker/blob/master/src/micro_http/src/server.rs#L219-L220)
In my opinion, `TempFile` should not be used in usage example so I was going to leave it as it is.

2. For `src/api_server/src/lib.rs::test_bind_and_run()`, current test works because `&'static str` implements `Copy` trait. When I replace the `path_to_socket` with `TempFile`, `path_to_socket` is moved to closure but it is referred later by current thread to read and write to socket.
  - moved: https://github.com/firecracker-microvm/firecracker/blob/master/src/api_server/src/lib.rs#L591
  - referenced: https://github.com/firecracker-microvm/firecracker/blob/master/src/api_server/src/lib.rs#L602
Do you have good idea to work around this issue?

**Comment by acatangiu** [comment]
> Should I update doc tests too?

It'd be useful so doc tests don't leave the unix-sock hanging around when they're done.
On the other hand, adding `TempFile` logic in doc examples will hurt readability, so I think we can stick with the current doc examples.

Indeed, you need to have each thread owns its object. You can do so by working with owned `String`s instead of `&str` references. Something like:

```rust
let mut tmp_socket = TempFile::new().unwrap();
tmp_socket.remove().unwrap();
let path_to_socket = tmp_socket.as_path().to_str().unwrap().to_owned();
let api_thread_path_to_socket = path_to_socket.clone();
```

**Comment by shioyama18** [comment]
> It'd be useful so doc tests don't leave the unix-sock hanging around when they're done.
> On the other hand, adding TempFile logic in doc examples will hurt readability, so I think we can > stick with the current doc examples.

Okay

> ```rust
> let mut tmp_socket = TempFile::new().unwrap();
> tmp_socket.remove().unwrap();
> let path_to_socket = tmp_socket.as_path().to_str().unwrap().to_owned();
>let api_thread_path_to_socket = path_to_socket.clone();
> ```

Thanks for the example. I'll create another PR after I update `src/vmm/src/vmm_config/vsock.rs::TempSockFile`.

**Comment by acatangiu** [comment]
Ideally do all of them in a single PR - different commits. Multiple PRs just adds extra load on reviewers, CI, and the merging process.

**Comment by shioyama18** [comment]
> Ideally do all of them in a single PR - different commits. Multiple PRs just adds extra load on
> reviewers, CI, and the merging process.

Sorry about that. I'll create single PR from next fix.
