### ISSUE TITLE
Create a Manifest of microVM Capabilites

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#186]
We need some kind of documentation, possibly in a programmatically consumable format, to express the device profile of the microVM to consumer. For example, those building minimal Guest OSs could use this manifest to customize device support.

**Comment by dianpopa** [comment]
It looks like  #1883 fixes this, right @raduweiss ?

**Comment by bbros-dev** [comment]
If #1883 doesn't close this (I think it misses the "possibly in a programmatically consumable format"), I think it is closed by #923 and #1212.

@dianpopa if you think it adds value I could insert into #1881 a 'complete' example of the JSON 'document'?

**Comment by dianpopa** [comment]
Hi @bbros-dev , sorry for the late reply, it is just now that I saw your proposal. I think the method you suggested of inserting an example of a complete microvm config with all the required fields clearly adds value. Feel free to post a PR with the suggestion. Thanks for the contribution!

**Comment by bbros-dev** [comment]
My working assumption is that this JSON should be valid uVM configuration - that is if passed to Firecracker it will run without error.

Are there configuration elements that are mutually exclusive?

**Comment by dianpopa** [comment]
The only thing that comes to mind is the `BootSource` representation and `DriveConfig`, i.e specifying an `initrd_path` in the `BootSource` (https://github.com/firecracker-microvm/firecracker/blob/master/src/api_server/swagger/firecracker.yaml#L734) will not make sense with a `DriveConfig` that specifies a root device (https://github.com/firecracker-microvm/firecracker/blob/master/src/api_server/swagger/firecracker.yaml#L762) since the system will use the provided `initrd_path` to load the filesystem. What you could do is provide 2 microvm configs: one using initrd_path and one using DriveConfig with a root device. wdyt?

**Comment by dianpopa** [comment]
A manifest of microVM capabilities can be found in the https://github.com/firecracker-microvm/firecracker/blob/v1.0.0/tests/framework/vm_config.json. This can be programatically consumed to configure a microVM from commandline. See #1212.
