### ISSUE TITLE
[Feature] Plugin System for additional features.

### ISSUE THREAD

**Issue by Cellebyte** [firecracker-microvm/firecracker#1900]
## Idea
Hey I am currently thinking on a plugin system for firecracker.
Is it possible to implement such a thing or is it out of the scope of the firecracker project?
Because it could be added towards such a system to support other features outside of the scope of this project like other storage providers or PCIe passthrough or other functions.

## Proposal
Adding some hook and plugin system which has a predefined API interface to extend the functionality and add features beyond the scope of this project.
Adding also a path on the API where you can register your plugin like simple CRDs in K8s. But in a basic way.

## From where my idea comes.
We are thinking on to remove QEMU from Hypervisor installations and use Firecracker as an option. But for that we need a plugin which directly attaches storage to the VM without using HostPath (Network remote Storage).
And a way of hook in to configure our specific network config on VM Provider for migration of VMs.
So that we can easily migrate those VMs on the fly between hosts. Supporting this as plugins would be a great option without putting the need on developing all these features directly in the firecracker project. 

## More Ideas?
What do you think about that idea, is it something which fits or is it not scoped by the firecracker project?

**Comment by raduweiss** [comment]
Hi @Cellebyte! We have been considering something like this, thinking of it in terms of "Specialized Firecracker Variants".

The use case you present above is part of that: Firecracker is supposed to maintain a minimal attack surface, have minimal overhead, and over time accumulate more and more defense in depth measures. This conflicts with adding more features, *but* only if all those features are there all at the same time. And so if we have a good way to "productize" several variants of Firecracker, we could have both.

We haven't spend too much time on this problem, but it seems to require doing three things very well:

1. **Build flexibility**, easily getting a build with the features set you want, including API, docs, plus all internal components);
2. **Adjustable specifications** per variant. E.g., we're adding performance acceptance tests now to Firecracker, and we'll want to run them all the time. But some features will make performance trade-offs (for example VMs with 48 cores vs network throughput and snapshot restore time), so we need a good way to adjust SLAs per release, but then apply all the same quality testing.
3. **Scaling security testing**, since with more variants we need to automate a lot of the security testing work to keep development agility.

I think it's very likely that we will do these things, but we haven't yet gotten tot he point of prioritizing/planning this. Still, learning about your use case is one more data point in favor :)

**Comment by Cellebyte** [comment]
@raduweiss

 I am not thinking on completely packing those plugins/hooks into firecracker but rather allow to build a version which supports adding plugins by calling a remote lib for a hook or extra functionality. This API should be as simple/minimal as needed for the type of hardware plugin.
Their should be some generic interface for the most needed stuff like network/storage and PCIe (whereas PCIe is something which should be disabled in a normal plugin enabled build because it makes the system exploitable by adding it).

Some UseCases I could think of:

### Network.

* Directly Speak to a VTEP or VLAN on the Network.
* Configure some more complex setup than DHCP
  * like BGP announced VMs or BGP Anycasted VMs

### Storage
* Directly attach to a Network Storage System via some external lib.
* Support higher Throughput and not rely on the host Kernel for Storage passthrough via host mounts.


### PCIe
* using a Network Card directly inside the VM to build LBs/NATs via EBPF or netfilter.
* using a Graphics Card directly inside the VM to support isolated ML workloads.

**Comment by raduweiss** [comment]
@Cellebyte , sorry for the late reply. Thanks for enumerating the use cases, that puts the issue in focus.

Do you mean users would build/test/qualify versions with plugins themselves? That can often imply non-intuitive trade-offs. For example, passing through hardware won't work with demand fault paging / memory over-subscription, and depending on what kind of network features are added, snapshot-restore will require additional work to function in the new context. 

My personal take, and I'm happy to have a discussion around this, is that there's are two directions that make sense:
1. Firecracker / a small number of Firecracker Specialized Variants has/have a limited but very secure, high performance, consistent, and easy to use set of features. This Firecracker(s) can be deployed as-is and will cover most serverless multi-tenant execution isolation use cases that we know of. These Firecracker's are also very well tested as a whole.
2. For other cases that don't fit and where large changes are needed anyway, it might be better to build things up from basic blocks rather than to alter Firecracker. This is what the [rust-vmm community](https://github.com/rust-vmm/community) is for (over time, a large part of Firecracker's components will come to be imported from rust-vmm).

In any case, this sounds like an interesting topic to chat about, and we will be happy to dive deep in those use cases and learn more. Some of the network and storage use cases were already on our radar for 2021. If you're interested chatting, let us know.
