### ISSUE TITLE
How to execute a script file when a Firecracker microVM startup?

### ISSUE THREAD

**Issue by Aceysx** [firecracker-microvm/firecracker#1947]
I went through [Get Start Guide](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md) and [api_request_doc](https://github.com/firecracker-microvm/firecracker/tree/master/docs/api_requests) to find a way to execute a script when start a microVM? But there is not way to do it.

Is there a way to achieve it? I want to run some script when a vm startup or execute a script without login.

**Comment by gc-plp** [comment]
Hi @Aceysx. 

In principle, Firecracker is a virtual machine manager (VMM) that is responsible for creating and managing virtual machines. 
Once a virtual machine is launched, Firecracker cannot interact with the virtual environment that it has just created, since each environment can have its own specific ways of communicating with the outside.

In order to run a script on startup, you need to build a rootfs that will execute that script for you.
For example, if you build a rootfs that is managed by systemd, you can follow [this](https://askubuntu.com/questions/919054/how-do-i-run-a-single-command-at-startup-using-systemd) guide on how to run a script on startup.
