### ISSUE TITLE
Firecracker can start guests without a block device, but we don't have a test for it

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#1972]
By design, Firecracker can start guests without block devices, but we don't test for this in [test_drives.py](https://github.com/firecracker-microvm/firecracker/blob/master/tests/integration_tests/functional/test_drives.py). There might be other tests that implicitly test this, and we should also look at the corresponding network interface situation (that one is also optional).

**Comment by bbros-dev** [comment]
To my mind the keyboard and console are also optional:

* User applications that shutdown on completion are not uncommon, hence no need for the keyboard `SendCtrlAltDel`.  A zombie guest will likely be investigated and can have its process killed.
* Production VM are more likely to have SSH access (if any) and console access is, to my mind a dev-phase feature.
* we agree that no-network use cases are natural.

That leaves the vsock - my (limited) understanding is vsock relates to containerized use cases, in which case I'd prefer to have it absent.

So all devices are optional?

**Comment by rpaul98** [comment]
Hi, @edengarza, @amaniduncker, and I are students at UT and are looking to contribute to an open source project for our virtualization class. We were wondering if we could get assigned to this issue.

Thanks!

**Comment by dianpopa** [comment]
Hi,

Indeed Firecracker can boot without a block device and this is tested implicitly by [this integration test](https://github.com/firecracker-microvm/firecracker/blob/master/tests/integration_tests/functional/test_initrd.py#L19). You can see there that we do not attach anything apart from a serial that helps with testing that Firecracker has booted successfully. Additionally, the ability to boot without a serial is tested in several integration tests, so that scenario is also exercised. As a consequence, the answer is yes, all devices are optional. I will close the issue, feel free to reopen if any more details are needed.
