### ISSUE TITLE
Separate allocate slot function in MMIO allocation and IRQ allocation

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#2014]
The allocate_slot takes care of two different actions:
- allocating a slot
- allocating an IRQ

For once, this makes the function to be improperly name (because it is not only allocation a slot, but also an irq). Having these two actions as part of the same function is problematic because while all MMIO devices do require a slot, not all MMIO devices require an IRQ. This later problem has been addressed in PR #1921 by having an input parameter which toggles whether an IRQ is needed or not. Yet another problem is that now because the function takes care of both the MMIO slot allocation and the IRQ allocation, the registering of the IRQ in KVM with kvm_register_irqfd takes place in a completely different place in the code. Allocating an IRQ and registering it to KVM should be handled in the same place because the reason for allocating that IRQ is to associate it with a device in KVM.

More on the topic in this conversation: https://github.com/firecracker-microvm/firecracker/pull/1921#discussion_r442159543

**Comment by dianpopa** [comment]
Hi,

@andreeaflorescu my suggestion here would be to just rename the function `allocate_new_slot` to `register_mmio_resources`, similar to what this function is named in [vm-device](https://github.com/rust-vmm/vm-device/blob/master/src/device_manager.rs#L208). 
In regards to allocating the IRQ and registering it in the same place, this would imply significant refactoring that I think is not worth the effort since our goal should be to switch to rust-vmm's vm-device. What are your thoughts on this?
