### ISSUE TITLE
Freeze devtool pip package versions

### ISSUE THREAD

**Issue by gc-plp** [firecracker-microvm/firecracker#2161]
## Describe the bug

The devtool containers that we currently build are not reproducible.

If we build the container at one point in time and rebuild it after a period of time when the packages receive new updates, we may get a different container.

## Expected behaviour

The pip packages in devtool should contain fixed versions.

**Comment by alindima** [comment]
I think the issue originated from this: when modifying the dockerfile and creating a new image tag, you may also update pip packages to their latest versions, without knowing it.
This can result in breaking changes, similar to one we recently had: a new version of pylint complained about some uses of `super()` that we had to modify in order to make the integration test pass. See [this commit](https://github.com/firecracker-microvm/firecracker/commit/cc63335bc82a7f1166409cf236b1403732a9ec25).

This kind of issue can extend to other python packages, potentially introducing breaking changes with their latest versions.
