### ISSUE TITLE
Inconsistent error reporting across devices.

### ISSUE THREAD

**Issue by bbros-dev** [firecracker-microvm/firecracker#2173]
## Describe the bug

Per RFC issue #1866 / PR #1883: 

>We do not have yet an unified interface for expected responses if users do not respect mandatory requirements of an API endpoint.

and

> We do not have a documentation for the error messages returned in response to drives/{id} or network-interfaces/{id}. I would suggest you to mention the returned errors response code for drives/{id} and mention also that network-interfaces/{id} is considered as no-op in case of error. This is not unified across devices. Feel free to open an issue for this as well.

## To Reproduce

Issue is identified per @iulianbarbu comments in  PR #1883

## Expected behaviour

Consistent error behaviour

## Environment

- Firecracker version.

```bash
$ firecracker --version
Firecracker v0.21.1
```
- Host and kernel version.
```bash
$ uname -a
Linux desktop.local.lan 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- Rootfs used: Not relevant
- Architecture: ` x86_64`

## Additional context

**How has this bug affected you?** Consuming Firecracker errors requires different logic depending on the API-device pair. 

**What are you trying to achieve?** Robust error handling.

**Do you have any idea of what the solution might be?** Single code path for Firecracker API-device pair error handling?

## Checks
- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by iulianbarbu** [comment]
Thanks for logging the issue!

I've dived deep more into the issue and it seems that we propagate the errors as an HTTP response for `network-interfaces/{id}` as well, rather than considering them as a no-op. Sorry for the confusion.

My misunderstanding came from the fact that we have two levels of error propagation:
1. First level is represented by primitives which execute the core of a `VmmAction` (e.g. [update_block_device_path](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/rpc_interface.rs#L480) or [update_net_rate_limiters](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/rpc_interface.rs#L531), which mutates the configs of the devices and in case of failure must return `vmm_config` errors, as in [DriveError](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/vmm_config/drive.rs#L21) or [NetworkInterfaceError](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/vmm_config/net.rs).
2. Second level is represented by the `VmmAction` handling context, which decides how to propagate the error from the first level, as in mapping those `vmm_config` errors to `VmmActionError`s.

The inconsistency or misalignment between `drives/{id}` and `network-interfaces/{id}` is that [update_net_rate_limiters](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/rpc_interface.rs#L531) returns an [ActionResult](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/rpc_interface.rs#L341) in the stead of a `vmm_config` error: as in [NetworkInterfaceError](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/vmm_config/net.rs).

This issue must address this inconsistency.

**Comment by kumargu** [comment]
Hi  @iulianbarbu , it seems like recently there was some work done on the error propagation in this [commit](https://github.com/firecracker-microvm/firecracker/commit/91c90d577a228b96b482eb66c81bca25fd3eb64a)

Both [update_block_device_path](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/rpc_interface.rs#L607)  and [update_net_rate_limiters](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/rpc_interface.rs#L618) (now) propagates VmmActionError. 

[update_net_rate_limiters](https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/rpc_interface.rs#L618) now has a nested Error Context for better error visibility.
```
NetworkConfig(DeviceUpdate(VmmError{ kind: Some Error }))
```

Let me know if this issue is still relevant, happy to spend more time investigating.

**Comment by iulianbarbu** [comment]
I think we just need to update the `device-api.md`. It seems that we return always 400 - Bad Request error responses in return to API requests [1]. Currently, we state in the `device-api.md` that:
``` 
If the device (column) is omitted from a uVM definition, a call to one of the API Endpoints will return a result that depends on the device (see issue #2173).

    * API calls related to drives/{id} result in 400 - BadRequest - HTTP response if the block device identified by id was not previously configured.
    * API calls related to network-interfaces/{id} result in 400 - BadRequest - HTTP response if the network device identified by id was not previously configured.
```

We can squash the information related to what status code responses we get in response to `network-interfaces/{id}` and `drives/{id}` into a single entry. Also, we can close this issue once we update the `device-api.md` doc.

[1] https://github.com/firecracker-microvm/firecracker/blob/master/src/api_server/src/parsed_request.rs#L128
