### ISSUE TITLE
[Bug] Sporadic Balloon test failing on aarch64

### ISSUE THREAD

**Issue by acatangiu** [firecracker-microvm/firecracker#2276]
## Describe the bug

```
=================================== FAILURES ===================================
_______________ test_size_reduction[debian_with_ssh_and_balloon] _______________
integration_tests/functional/test_balloon.py:385: in test_size_reduction
    assert first_reading - second_reading >= 10000
E   assert (88692 - 80004) >= 10000
```

**Comment by georgepisaltu** [comment]
In order to solve this issue, we need to establish the same baseline for RSS right after boot in all the balloon integration tests. This can be done by inflating the balloon to a certain size just a bit smaller than the available memory of the VM after boot (for a 256 MiB VM this value is roughly 200 MiB) and then deflate it back to 0.

This solution is currently implemented only in `integration_tests/functional/test_balloon.py::test_reinflate_balloon` and using it in all of the remaining tests would likely fix this intermittent failures.

**Comment by HQ01** [comment]
Hi @georgepisaltu  should I take #2258 as a reference if I would like to help fix this issue?

**Comment by dianpopa** [comment]
@gc-plp does this still replicate after adding retry functionality for "get_stable_rss_mem_by_pid", I personally have not seen any balloon test failing on aarch64 since then...

**Comment by gc-plp** [comment]
@dianpopa I haven't either. But we can try running it in a loop.

**Comment by acatangiu** [comment]
I saw this on a slightly older branch, it did not have the `get_stable_rss_mem_by_pid` commit.

Closing it for now, we can reopen if we see it again.
