### ISSUE TITLE
Does Firecracker support AMD Secure Encrypted Virtualization (SEV)?

### ISSUE THREAD

**Issue by CodingYuanLiu** [firecracker-microvm/firecracker#2332]
## Why is this feature request important?  What are the use cases?  Please describe.

AMD Secure Encrypted Virtualization (SEV) is a hardware feature provided by AMD, designed to isolate virtual machines from the hypervisor.

## Describe the desired solution
So far, we can use QEMU to start a VM with SEV enabled. If firecracker support SEV, we can use firecracker to replace QEMU and start a micro VM with SEV.

## Describe possible alternatives

Without the feature, I can only use QEMU to start a VM with SEV, so that I can not take advantages of firecracker's feature

## Additional context

No additional context
## Checks
- [y] Have you searched the Firecracker Issues database for similar requests?
- [n] Have you read all the existing relevant Firecracker documentation?
- [n] Have you read and understood Firecracker's core tenets?

**Comment by georgepisaltu** [comment]
Hi @CodingYuanLiu,

Firecracker does not support AMD Secure Encrypted Virtualization. I don't think Firecracker can support SEV as of right now because we provide snapshot capabilities and any operations that involve saving and restoring the memory and state of the VM are unsupported by SEV. From my research, it seems that with hardware evolution this barrier might disappear and we could look into this feature.

**Comment by CodingYuanLiu** [comment]
Thank you for your help. By the way, may I ask that how fast can firecracker start when restoring from a snapshot?

**Comment by georgepisaltu** [comment]
As you can see in our integration tests [here](https://github.com/firecracker-microvm/firecracker/blob/8553d64a0fa18b281cbeb757bbe350fde7cd6978/tests/integration_tests/performance/test_snapshot_perf.py#L35), we ensure we have a restore time of less than 8 ms in the tests, but we target 5 ms. The 8 ms value is only for testing purposes and comes from [this issue](https://github.com/firecracker-microvm/firecracker/issues/2027).

**Comment by CodingYuanLiu** [comment]
Wow that target is fantastic. Thank you a lot for your help.

**Comment by hpvd** [comment]
Since we are also interested in this, I did a little research:
seems to be possible now using `SEV Key Management`
`KVM implements the following commands to support common lifecycle events of SEV guests, such as launching, running, **snapshotting, migrating** and decommissioning.`
https://www.kernel.org/doc/html/v5.6/virt/kvm/amd-memory-encryption.html#sev-key-management

**Comment by hpvd** [comment]
also interesting from firecracker roadmap planning:
https://github.com/firecracker-microvm/firecracker/pull/4894

> The kata-containers initiative for confidential compute is interested in
> including Firecracker GPU support.

-> Do they run their container already on fire cracker with confidential compute (and now "only want to add PCIe pass through)?

**Comment by hpvd** [comment]
> Hi @CodingYuanLiu,
> 
> Firecracker does not support AMD Secure Encrypted Virtualization. I don't think Firecracker can support SEV as of right now because we provide snapshot capabilities and any operations that involve saving and restoring the memory and state of the VM are unsupported by SEV. From my research, **it seems that with hardware evolution this barrier might disappear and we could look into this feature.**

+1 on reopening this issue, or shall we create a new one?

**Comment by bdchatham** [comment]
Also +1 to reopening this issue. This would be a huge win for CC use-cases in multiple ways.

**Comment by JackThomson2** [comment]
Hi,

Thanks for the interest in this, unfortunately this currently is not on our roadmap. We will reopen this issue if this changes in the future
