### ISSUE TITLE
[Feature Request] vsock with connect-only and port-mapped semantics

### ISSUE THREAD

**Issue by jmillikin-stripe** [firecracker-microvm/firecracker#2451]
# Feature Request

A fairly common pattern for chroot-based sandboxes is the use of a UNIX socket for guest=>host communication. The general shape is:
* A privileged host service binds a socket at `/run/some-service/some-service.sock`
* The `/run/some-service` dir gets bind-mounted (with `ro`) into the guests.
* When a guest connects, the host process can use UNIX socket credentials to identify the guest process PID and then use cgroup/containerd state to bootstrap a client identity.

Firecracker's existing vsock support is almost capable of supporting this model, but there are two issues:
* The vsock has a UNIX socket created by the guest -- we don't want guests to be able to create sockets in what is effectively a privileged part of the host filesystem.
* Connections from the guest to the host use the numeric vsock port to compute the host's socket path.

This feature request is for a modified vsock mode that can allow connect-only (the guest can't `bind()`) and port-mapped (each vsock port connects to an explicitly named host socket) behavior.

## Describe the desired solution

Given the existing JSON of a Firecracker vsock config:
```json
{
      "vsock_id": "1",
      "guest_cid": 3,
      "uds_path": "./v.sock"
}
```

I would like new config fields to be added, which adjust how vsock ports are mapped to UNIX sockets.
* `"no_guest_bind": true` prevents the guest from being able to `bind()` on the vsock.
  * In this mode, the guest's listening UNIX socket is not created.
* `"port_to_uds_path": {port: "/some/path.sock", ...} ` causes connections from the guest to be sent to the named UNIX socket, mapped by port number.

(names/types are just for example, I have no strong opinion on the schema)

The resulting vsock config would look something like this:
```json
{
      "vsock_id": "1",
      "guest_cid": 3,
      "no_guest_bind": true,
      "port_to_uds_path": {
        "123": "/run/some-service/some-service.sock",
        "456": "/run/other-service/other-service.sock"
      }
}
```

## Describe possible alternatives

The primary alternative involves managing a tree of temporary directories, created per VM to contain sockets from host services.

This is less desirable because it increases the amount of host state involved in the connection path between untrusted guest processes and the privileged host services.

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by dianpopa** [comment]
Hi @jmillikin-stripe! Thank you for the detailed presentation of your usecase. We will dive deep into understanding your use case and will get back to you once we are clear on what it would take to implement the feature.

**Comment by alindima** [comment]
Hi @jmillikin-stripe. Thanks for opening the issue and your detailed explanation. I've started looking into this to better understand your use-case.

I'm taking your improvement ideas one by one:

> The vsock has a UNIX socket created by the guest -- we don't want guests to be able to create sockets in what is effectively a privileged part of the host filesystem.

There are two cases here:
1. host-initiated connections: Firecracker binds and listens on the `uds_path ` socket for incoming host connections. When receiving a `CONNECT X` packet on the UDS, it initiates a connection with the guest process listening on the vsock socket at port X.
2. guest-initiated connections: A host process binds and listens on `uds_path_X`, where X is the desired port. When receiving a connect packet from the guest at the said port, Firecracker issues a `connect()` on the socket. If there is no process on the host that did bind that socket, Firecracker will close the socket fd and send a connection reset packet to the guest.

The point I'm getting at is that guests are not allowed to bind sockets in the host. They merely try to connect to sockets that must have been created and `bind`-ed by other processes on the host. Does this make sense?

> Connections from the guest to the host use the numeric vsock port to compute the host's socket path.

I don't really understand the need for this. Is it just some syntactic sugar so that ports are not embedded in the socket name?

Looking forward to your input

**Comment by jmillikin-stripe** [comment]
> The point I'm getting at is that guests are not allowed to bind sockets in the host.

My apologies, I used "guest" to refer to the entire Firecracker process (both the sandbox and the virtualized kernel).

For Firecracker to create a socket at `uds_path` that receives incoming host connections, it must have write permissions in the socket's directory. It would be preferable if this permission was not necessary, and opting out of enabling incoming host connections seems like a clean solution there.

> I don't really understand the need for this. Is it just some syntactic sugar so that ports are not embedded in the socket name?

The purpose there is to make the mapping of ports to socket paths explicit in the configuration, and to allow the sockets to exist in different directories. This allows the Firecracker configuration to reference existing sockets at whatever location they're placed.

It might be easier to explain with an example. In the current Firecracker implementation, running the sandboxes requires a filesystem layout like this:

```
# pre-existing sockets in use by current sandbox approach (containerd or gVisor)
/run/
  some-service/
    some-service.sock
  other-service/
    other-service.sock

# temporary socket dirs used by Firecracker
/tmp/
  firecracker-sockets/
    sandbox_aaaa/
      vsock_uds # created by Firecracker
      vsock_uds_1 => /run/some-service/some-service.sock
      vsock_uds_2 => /run/other-service/other-service.sock
    sandbox_aaab/
      vsock_uds # created by Firecracker
      vsock_uds_1 => /run/some-service/some-service.sock
      vsock_uds_2 => /run/other-service/other-service.sock
```

Where each sandbox requires its own temporary sandbox directory, with symlinks crafted to point at the "real" sockets. These directory trees need to be created and garbage-collected by some separate tool.

With the proposed changes, the services' sockets could be referenced directly, so there's no need for symlink setup.

**Comment by alindima** [comment]
> My apologies, I used "guest" to refer to the entire Firecracker process (both the sandbox and the virtualized kernel).

Ah, this makes more sense now

> For Firecracker to create a socket at `uds_path` that receives incoming host connections, it must have write permissions in the socket's directory. It would be preferable if this permission was not necessary, and opting out of enabling incoming host connections seems like a clean solution there.

The recommended way of running Firecracker is via the jailer. The jailer sets up a separate directory for each VM and `chroot`s there before calling `exec()` into Firecracker. This will be the new root folder of the process, where the vsock uds would be created, as well as any other resources needed by Firecracker.

This is what happens currently for the API socket as well.

Using the recommened jailer removes the need for creating temporary socket directories for VMs (because the jailer does that for us) and is a way of containing the ability of Firecracker to create sockets in arbitrary parts of the host filesystem.

> The purpose there is to make the mapping of ports to socket paths explicit in the configuration, and to allow the sockets to exist in different directories. This allows the Firecracker configuration to reference existing sockets at whatever location they're placed.

I see your point. This is essentially a 1:1 mapping of the guest-initiated connections, with the purpose of renaming them to something that a host service would expect.

Having a static mapping here would not scale very well. The JSON request/configuration may quickly become fairly large and hard to read. Also, what happens if we want to dynamically change the mapping (say by adding a new guest-initiated connection socket path). We'd need to add a `/vsock` PATCH request that allows editing this mapping.

I see the value proposition you are making but this extra mapping something workload-specific and I think it's best to handle this at a higher level (the symlinks approach you mentioned being a good option)
I believe the added complexity would not justify the cause.

**Comment by jmillikin-stripe** [comment]
OK, since it seems like the recommended approach is to use a wrapper process and temporary directory anyway, I'll close this request.
