### ISSUE TITLE
[Perf] Use virtio packed queues to improve Firecracker emulated IO/network performance

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#2477]
# Feature Request

Improve Firecracker emulated network/IO performance via virtio packed queues.

## Describe the desired solution

Use [virtio packed queues](https://www.redhat.com/en/blog/packed-virtqueue-how-reduce-overhead-virtio) to improve Firecracker emulated IO performance. This should be transparent to Firecracker users.

## Describe possible alternatives

There are many approaches to improving Firecracker emulated IO/network performance. This is one of them.

## Additional context

[PoC here](https://github.com/serban300/firecracker/tree/virtio_packed_queues).

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by raduweiss** [comment]
Looks like this only provides a 2% improvement so it's not a low hanging fruit. @serban300 can you paste the data & conclusions of your investigation?

**Comment by serban300** [comment]
I tried 2 test scenarios. For both of them I used a m5d.metal machine.

**Note:** The `bitrate` results are rounded to 0 decimals, the `vmm thread load` and `bitrate / vmm thread load` results are rounded to 2 decimals. The rounding can lead to inexact numbers for the `bitrate / vmm thread load` metric.

## Scenario #1 ##

We start a number of microVMs with 8vCPUs and 16GB of RAM each. All the microVMs are pinned to the physical CPUs range 72-95 (NUMA node 1) using `taskset`. Each microVM runs an iperf server. On the host we start one iperf client per microVM. Each iperf client is pinned to 1 physical CPU in the range 24-47 (NUMA node 1) using `taskset`. The iperf clients are generating as much TCP traffic as possible for 60s host-to-guest, and then for 60s guest-to-host. In the meanwhile a `perf` process is monitoring the `task-clock` metric of the emulation thread of each microVM in order to determine the CPU load.

Results:

| #VMs | Split | | | | | | Packed | | | | | |
|-|-|-|-|-|-|-|-|-|-|-|-|-|
| | h2g | | | g2h | | | h2g | | | g2h | | |
|  | bitrate | vmm thread load | bitrate / vmm thread load | bitrate | vmm thread load | bitrate / vmm thread load | bitrate | vmm thread load | bitrate / vmm thread load | bitrate | vmm thread load | bitrate / vmm thread load |
| 1 | 24761 | 0.74 | 33281 | 22329 | 0.87 | 25607 | 31407 | 0.84 | 37389 | 23631 | 0.94 | 25086 |
| 2 | 48644 | 1.42 | 34160 | 41910 | 1.81 | 23180 | 58699 | 1.64 | 35880 | 45374 | 1.89 | 23982 |
| 4 | 103629 | 3.05 | 33977 | 83913 | 3.67 | 22865 | 103366 | 3.07 | 33714 | 81009 | 3.57 | 22666 |
| 8 | 175407 | 6.52 | 26919 | 136367 | 7.05 | 19343 | 174476 | 6.54 | 26658 | 137033 | 7.13 | 19211 |
| 12 | 197486 | 9.79 | 20172 | 170212 | 10.88 | 15647 | 185580 | 9.79 | 18956 | 170256 | 10.93 | 15573 |
| 16 | 168993 | 9.87 | 17127 | 164919 | 11.31 | 14583 | 164818 | 9.90 | 16650 | 164225 | 11.35 | 14464 |
| 20 | 156752 | 10.45 | 15002 | 161682 | 11.55 | 13996 | 153730 | 10.49 | 14654 | 159803 | 11.61 | 13762 |
| 24 | 149231 | 10.60 | 14074 | 157876 | 11.68 | 13518 | 148517 | 10.60 | 14008 | 156667 | 11.72 | 13364 |
| | | | 24339 | | | 18592 | | | 24739 | | | 18514 |


## Scenario #2 ##

We start a number of microVMs with 8vCPUs and 16GB of RAM each. All the microVMs are pinned to the physical CPUs range 72-95 (NUMA node 1) using `taskset`. Each microVM runs 8 iperf server. Each iperf server is pinned to 1 vCPU using `taskset`. On the host we start 8 iperf clients per microVM. All the iperf clients are pinned to the physical CPUs range 24-47 (NUMA node 1) using `taskset`. The iperf clients are generating 1Gbps of TCP traffic for 60s host-to-guest, and then for 60s guest-to-host. In the meanwhile a `perf` process is monitoring the `task-clock` metric of the emulation thread of each microVM in order to determine the CPU load.

Results:

| #VMs | Split | | | | | | Packed | | | | | |
|-|-|-|-|-|-|-|-|-|-|-|-|-|
| | h2g | | | g2h | | | h2g | | | g2h | | |
|  | bitrate | vmm thread load | bitrate / vmm thread load | bitrate | vmm thread load | bitrate / vmm thread load | bitrate | vmm thread load | bitrate / vmm thread load | bitrate | vmm thread load | bitrate / vmm thread load |
| 8 | 64000 | 3.85 | 16641 | 63928 | 5.03 | 12719 | 64000 | 3.86 | 16580 | 63932 | 5.03 | 12713 |
| 12 | 73212 | 4.81 | 15224 | 95887 | 6.78 | 14145 | 72958 | 4.83 | 15105 | 95887 | 6.77 | 14164 |
| 16 | 50683 | 3.62 | 14020 | 57692 | 4.09 | 14116 | 50348 | 3.62 | 13904 | 58170 | 4.14 | 14064 |
| 20 | 37274 | 3.04 | 12273 | 44862 | 3.49 | 12847 | 36349 | 3.05 | 11929 | 44289 | 3.50 | 12658 |
| 24 | 33415 | 3.05 | 10974 | 40550 | 3.33 | 12192 | 31821 | 3.00 | 10614 | 40210 | 3.34 | 12053 |
| 28 | 43269 | 3.41 | 12689 | 38789 | 3.32 | 11670 | 35852 | 3.22 | 11120 | 37466 | 3.27 | 11443 |
| | | | 13637 | | | 12948 | | | 13209 | | | 12849 |

**Comment by serban300** [comment]
This is not a low hanging fruit, but we also don't have enough data to say that it's not worth supporting. We will postpone it for a deeper investigation later.

**Comment by xmarcalx** [comment]
Closing this issue and removing it from the roadmap because according the data of the previous investigation, this is not a solution we will follow to achieve performance improvements.
