### ISSUE TITLE
[Bug] Possible atomicity violation when logger metric init

### ISSUE THREAD

**Issue by BurtonQin** [firecracker-microvm/firecracker#2486]
# Describe the bug
https://github.com/firecracker-microvm/firecracker/blob/9e94be71f4a079bf8fafd8f3c801750e744d930f/src/logger/src/metrics.rs#L107-L118

I wonder if the result is expected If `is_initialized.load()` and `store()` in `init()` are interleaved by another `store()` from another thread.
|Thread-1|Thread-2|
|---|---|
|load() == false|load() == false|
||init-1|
||store(true)|
||write|
|init-2||
|store(true)|

## To Reproduce

I found it through static analysis.

## Environment

None.

## Additional context

Perhaps we can use CAS to replace the separate Load&Store like `call_init()` in init.rs?

## Checks

None.

**Comment by gc-plp** [comment]
Hi @BurtonQin. This looks like a valid bug in the situation where multiple threads are used. In this specific situation I believe that Firecracker initializes the metrics module on a single thread, but we will look into this either way.

Could you point us to the static analysis tool that you have used? I took a look at your profile and found [rust-lock-bug-detector](https://github.com/BurtonQin/rust-lock-bug-detector). Is this the project?

**Comment by BurtonQin** [comment]
It is still WIP. I will release it after some refactoring work.

**Comment by sandreim** [comment]
Looking at this from close range, there is indeed an issue. Looking at how this is used in firecracker, the initialization happens in a single threaded context, here: https://github.com/firecracker-microvm/firecracker/blob/master/src/firecracker/src/main.rs#L197 . This calls into https://github.com/firecracker-microvm/firecracker/blob/master/src/vmm/src/vmm_config/logger.rs#L129 which performs the actual initialization long before any other threads are spawned.

**Comment by sandreim** [comment]
I think that it would make sense to either find a way to fix this or specifically document that Logger full initialization should not be involved in racing scenarios - called from multiple threads. Are there any other concerns here ?

**Comment by sandreim** [comment]
Ah, I just noticed you are referring to metrics and not logger, I was mislead by the title 😄 and the similar code. So yeah,  please disregard the above. We have to check if we init from single threaded scenario and if not, do it. Still, this code is not safe and can cause further problems, and maybe another fix works better.

**Comment by gc-plp** [comment]
Seems that all `METRICS.write` calls are handled in the same thread, indeed.

We initialize the metrics through [this call](https://github.com/firecracker-microvm/firecracker/blob/2f19452cddce5adfa8f5fb1c9e7fc8c64d4084df/src/vmm/src/vmm_config/metrics.rs#L37), with calls being made when [initializing from JSON](https://github.com/firecracker-microvm/firecracker/blob/b36bf7195a4e7de706b30bbdf298e40947cabca6/src/vmm/src/resources.rs#L112) or through the [API server](https://github.com/firecracker-microvm/firecracker/blob/b36bf7195a4e7de706b30bbdf298e40947cabca6/src/vmm/src/rpc_interface.rs#L290).

Unless I missed something, we call `metrics.write` in a few places:
- [main.rs](https://github.com/firecracker-microvm/firecracker/blob/c265e37f35337649b6c735640e3cd9d0d0fc6cff/src/firecracker/src/main.rs#L59), which is handled by the main thread.
- [signal_handler.rs](https://github.com/firecracker-microvm/firecracker/blob/9e94be71f4a079bf8fafd8f3c801750e744d930f/src/vmm/src/signal_handler.rs#L214) handled by the main thread.
- [VMM lib.rs](https://github.com/firecracker-microvm/firecracker/blob/dcd132fae1756fe9a21b4ccba7bcc9a70d40efdc/src/vmm/src/lib.rs#L353) handled by the main thread.
- [rpc_interface.rs](https://github.com/firecracker-microvm/firecracker/blob/b36bf7195a4e7de706b30bbdf298e40947cabca6/src/vmm/src/rpc_interface.rs#L550) handled by the main thread.

As @sandreim mentioned, we need to find a better solution for this. 

A follow up question would be, do we need to use an `AtomicBool` since we operate the metrics single threaded?

**Comment by georgepisaltu** [comment]
I looked into this and indeed `metrics.write` is only called from a single thread, this also seems to be the case for `metrics.init`.

Seeing as the static struct responsible for the metrics has the fields:
```
    metrics_buf: Mutex<Option<Box<dyn Write + Send>>>,
    is_initialized: AtomicBool,
    pub app_metrics: T,
```
This means that only `app_metrics` actually is accessed in multiple threads.

Unfortunately, because this struct is part of a `lazy_static!` declaration, we can't remove the synchronization mechanisms from the `metrics_buf` and `is_initialized` fields because `lazy_static` enforces thread safety on all members.

I think it would be best to just add a comment on the `metrics.init` path which states that these functions should not be used in a multi-threaded context.

Another option that I thought of would be to place `metrics_buf` and `is_initialized` in a wrapper struct which then would be further wrapped in a mutex in the metrics struct. This way, we eliminate the race condition described in the issue, with the downside that this is not really necessary.

I found that refactoring the whole `lazy_static! { metrics }` thing to be really difficult, but I am listing it as an option nonetheless.

Let me know what you think about this.
