### ISSUE TITLE
Make errors more specific and user friendly

### ISSUE THREAD

**Issue by sandreim** [firecracker-microvm/firecracker#2520]
Some of the snapshot error messages are very vague like reported here: https://github.com/firecracker-microvm/firecracker/pull/2503#discussion_r600533833

We  need to identify and fix the API and log error messages that need improvement.

**Comment by lyuyuan** [comment]
Hi, has anybody planned to work on this? If not, I'd like to give it a try.

**Comment by lyuyuan** [comment]
It seems the translation from FC version to snapshot version is done by performing a static map lookup in [`vmm::persist::get_snapshot_data_version`](https://github.com/firecracker-microvm/firecracker/blob/6292f3289a8a5acdbd15d7e042a89ece95c31fb4/src/vmm/src/persist.rs#L272-L290). And if the provided version string is not found in [`FC_VERSION_TO_SNAP_VERSION`](https://github.com/firecracker-microvm/firecracker/blob/6292f3289a8a5acdbd15d7e042a89ece95c31fb4/src/vmm/src/version_map.rs#L27-L36), it will anyways write the same error message for an `InvalidVersion` error.

What I think we can do here is checking  whether the version is in the format of `x.xx.x`, and if not, respond with message that indicates it is a bad input. Otherwise, we respond with message that indicates the version does not have snapshot support.

What do you think?

**Comment by acatangiu** [comment]
Based on [this comment](https://github.com/firecracker-microvm/firecracker/pull/2524#pullrequestreview-644360675), this issue is not completely done.

**Comment by lyuyuan** [comment]
@acatangiu @sandreim thanks for approve and merge the PR.
To clarify, this ticket aims to refactor all FC API response error messages, not just snapshot creation/loading. If so, I will start by going through functional tests to see if their are scenarios where the message can be improved. Please also feel free to let me know if you have code path in mind that you want to improve.
