### ISSUE TITLE
support ceph block storage

### ISSUE THREAD

**Issue by aep** [firecracker-microvm/firecracker#2720]
supporting ceph should be a matter of plugging librbd into src/devices/src/virtio/block/device.rs

i could contribute that, if its an acceptable feature.

**Comment by alindima** [comment]
Hello and thanks for opening the feature request.

We would need to dive deep into the topic before we can reach a conclusion, so any further information would be greatly appreciated, like: what problem would this feature solve and detailing your use case of this feature

**Comment by aep** [comment]
Hi. I don't understand the question. The use case is to mount rootfs from ceph instead of local fs.

 We're not an aws customer if that's the point.

**Comment by iggy** [comment]
I brought this up on slack a while back (looks like almost 3 years ago, so things may have changed), and was told it wasn't something they were going to work on instead leaving it to other layers of the stack to handle. Imo, that's unfortunate because that basically means relying on the kernel rbd driver which is constantly woefully behind (even in upstream kernels... not to mention vendor kernels).

**Comment by gregorybrzeski** [comment]
@iggy I have a feeling that if a nice design document was submitted for discussion and there was someone willing to develop this feature, there wouldn't be any objections. Would you be willing to contribute?

Just a voice of someone who is following this project for a while now.

**Comment by alindima** [comment]
Hello. Let's use this issue as a medium for collecting data on the usefulness and implications of adding a ceph backend. So first of all let's work backward from the problem solved by the ceph backend and how and if it is better than the generic file abstraction Firecracker is currently using.

Using generic abstractions is one of the mechanisms that have enabled Firecracker to remain minimal, secure and with a low overhead. The file abstraction has so far been powerful enough to enable most Firecracker use-cases.

Sometimes, however, these abstractions don't work or add too much overhead, and I guess that's the problem you are trying to solve here. Let's use this issue to document the limitations of the current design and benefits of the proposed enhancement.

If it turns out that we do need a better abstraction, we would want to look at building some sort of pluggable block device backends instead of baking in multiple specific ones (like ceph). This comes from our minimalism tenet, Firecracker is a scalpel and not a swiss army knife.

Doing that would require a very thorough design, documentation, a clear need, significant contributions from the community and would definitely take time.

But we're getting ahead of ourselves. Let's start with your use case, needs and experienced limitations with the current design. For posterity let's document as much detail and context as possible on this issue.

**Comment by aep** [comment]
i figured qemu already has ceph support and actually starts faster than firecracker so we're going to use that. we can close this issue
