### ISSUE TITLE
[Documentation] What is Firecracker? E.g. do typical guests run their own (linux) kernel?

### ISSUE THREAD

**Issue by joernheissler** [firecracker-microvm/firecracker#2723]
I can't find the answer to the question neither on https://firecracker-microvm.github.io/ nor on https://github.com/firecracker-microvm/firecracker#what-is-firecracker

Do the guests have their on (vanilla) Linux Kernel? Can I run complete Operating Systems like Debian as a microVM? What kind of workload is usually run inside the microVM?

Could you Please clarify this in your top level docs? Thanks!

**Comment by alindima** [comment]
Hello.
Yes, Firecracker guests run full-fledged linux guests (with versions greater than 4.14). However, Firecracker has a minimal device model, exposing only a couple of devices: virtio-block, virtio-net, virtio-vsock and a couple of others. So the kernel needs to usually be compiled by hand, so that it includes the specific drivers needed to work with Firecracker.

> Can I run complete Operating Systems like Debian as a microVM?

So yes, as long as your operating system consists of a linux kernel compatible with Firecracker and a root filesystem.
[Here](https://github.com/firecracker-microvm/firecracker/blob/main/docs/rootfs-and-kernel-setup.md) are some instructions we have for compiling kernel and building a rootfs.

Actually, the rootfs that is downloaded via the [getting started guide](https://github.com/firecracker-microvm/firecracker/blob/main/docs/rootfs-and-kernel-setup.md) is that of a stripped down ubuntu 18.04. I highly recommend going over this guide in order to get more familiar with Firecracker.

As for the usual workloads, we state that Firecracker is specifically tailored for serverless workloads. This includes (but not limited to) anything you can imagine would be running in a serverless function, like AWS Lambda. We have a list of customers [here](https://firecracker-microvm.github.io/), which can help you get an idea of the typical workloads.

I think the documentation we have is clear enough, so I'm going to close this issue. Feel free to join our slack workspace and ask any further questions you may have there: https://join.slack.com/t/firecracker-microvm/shared_invite/zt-oxbm7tqt-GLlze9zZ7sdRSDY6OnXXHg
