### ISSUE TITLE
[Bug] GET `/vm/config` returns empty config data for VMs resumed from a snapshot

### ISSUE THREAD

**Issue by alindima** [firecracker-microvm/firecracker#2783]
# Describe the bug

A `GET` request on `/vm/config` should return the full VM configuration.
For a VM built from requests or a JSON, this works as expected.
However, for a VM created from a snapshot, this only includes an incorrect machine-config (the default one), with the rest of the fields left blank:

Sample output:

```
{'balloon': None, 'drives': [], 'boot-source': {'kernel_image_path': '', 'initrd_path': None}, 'logger': None, 'machine-config': {'vcpu_count': 1, 'mem_size_mib': 128, 'ht_enabled': False, 'track_dirty_pages': False}, 'metrics': None, 'mmds-config': None, 'network-interfaces': [], 'vsock': None}
```

## To Reproduce

1. Start a Firecracker VM.
2. Pause and create a snapshot.
3. Launch a new Firecracker process and load the snapshot.
4. Issue a GET request on `/vm/config` to get the full config.

## Expected behaviour

Should return the correct configuration

## Checks

- [x] Have you searched the Firecracker Issues database for similar problems?
- [x] Have you read the existing relevant Firecracker documentation?
- [x] Are you certain the bug being reported is a Firecracker issue?

**Comment by summerlinryan** [comment]
Hey I'm pretty new to Rust, Firecracker, and OSS in general but I recently have been doing some OS development in Rust and though this was a great project for me to try to contribute to. I'd like to take a shot at solving this bug if that's alright with the maintainers. I'm able to reproduce it and think I see the underlying root cause. I'm developing a solution now and plan to submit a PR as soon as I've got it tested/documented.

**Comment by alindima** [comment]
Hi! Great, thank you and looking forward to your PRs!

**Comment by summerlinryan** [comment]
@alindima 

Here's a summary of what I've determined so far and the parts that I'm a little bit confused on. The `rpc_interface::RuntimeApiController` has a reference to the `vm_resources` which is what is returned in the `/vm/config` API response, but the root issue is that the `vm_resources` are never set on that controller when the `rpc_interface::PrebootApiController::load_snapshot` is used to load the snapshot. I'm currently trying to figure out how to reconstruct a `VmResources` object in the `persist::restore_from_snapshot` function from the `MicrovmState` and the `Vmm` which I plan on returning to the `rpc_interface::PrebootApiController::load_snapshot` method. I know this is a bit verbose but I was just looking to see if you had any feedback on whether or not this seemed like a reasonable approach?

**Comment by acatangiu** [comment]
Sounds legit!
You can populate `resources.vm_config` with data from `vmm.guest_memory` and `vmm.vcpus_handles`.
You can populate all resources::devices using `vmm.mmio_device_manager.for_each_device()`.

`boot_config` is lost unfortunately - it's not saved in the snapshot and cannot be recovered in the resumed microvm. I guess it's fine for it to be `None` in case of a VM resumed from snapshot (this particular microvm instance wasn't actually booted but came from a snapshot).
If there's ever an actual need to get historical `boot_config` data, Firecracker can, at that point, add support for it as an enhancement.

**Comment by alindima** [comment]
The proposed solution as well as @acatangiu's suggestions sound good to me as well!

**Comment by summerlinryan** [comment]
Thanks for the feedback guys. I have made more progress but still haven't fully got things working. My current issues are:
- When trying to use `vmm.mmio_device_manager.for_each_virtio_device` to set all of the block devices on the `VmResources` that I'm when loading a snapshot, I get a runtime error related to `intercepting signal 31, code 1` and a `bad syscall(4)`. 
- With the `PrebootApiController::vm_resources` is a reference to a `VmResources` object so I'm having lifetime issues. Specifically, the `VmResources` that I construct in `persist::restore_from_snapshot` and return doesn't live long enough. 
I wasn't planning on submitting a PR until everything is done but I'm wondering if I should submit one soon so that you guys can see the code I have so far which might make it easier to give specific feedback on what I'm doing wrong. Since I'm new to open source, just not sure of the best way to show specific code that is in progress without submitting an incomplete PR. Let me know what you guys think is the best approach for me to take. I've put quite a bit of time into learning about everything and trying to solve this and I feel close but maybe this bug is just too difficult for me to solve at the moment.

**Comment by alindima** [comment]
Good to see you are making progress!

> When trying to use vmm.mmio_device_manager.for_each_virtio_device to set all of the block devices on the VmResources that I'm when loading a snapshot, I get a runtime error related to intercepting signal 31, code 1 and a bad syscall(4).

This is caused by seccomp. After loading the snapshot and booting the VM, seccomp filters are installed that only allow a hardcoded list of system calls to be made. It seems that you are calling `stat` in there, which is not allowed.
Here is the default allowlist for x86: https://github.com/firecracker-microvm/firecracker/blob/main/resources/seccomp/x86_64-unknown-linux-musl.json (note that it's per thread).
If you add a syscall to the allowlist and compile Firecracker, the new binary will allow that system call at runtime.

For prototyping purposes only, you may also run Firecracker with `--no-seccomp`.

> I wasn't planning on submitting a PR until everything is done but I'm wondering if I should submit one soon so that you guys can see the code I have so far which might make it easier to give specific feedback on what I'm doing wrong. Since I'm new to open source, just not sure of the best way to show specific code that is in progress without submitting an incomplete PR. Let me know what you guys think is the best approach for me to take. I've put quite a bit of time into reading through code and documentation and trying to solve this and I feel close but maybe this bug is just too difficult for me to solve at the moment.

I encourage you to open a Draft PR so that we can see your code and provide feedback directly there.
I think we can work through the lifetime issues once we see the work-in-progress code.
Thanks for all the effort so far!

**Comment by alindima** [comment]
The bulk of the issue was solved in this PR: https://github.com/firecracker-microvm/firecracker/pull/2806
The left items are:
- net devices MAC addresses are reported as all zeros if left unconfigured.
- the `machine_config.smt` and `machine_config.cpu_templates` values are lost (we could persist them in the VmState).
- `boot_source` is lost (IMHO this behaviour is OK, since boot source does not make sense for a VM restored from snapshot. the vmlinux path may not even be present on the machine any more)

I believe we should chat some more on whether those loose ends are worth implementing. Any opinions are welcome

**Comment by acatangiu** [comment]
> I believe we should chat some more on whether those loose ends are worth implementing.

my 2c is don't put in the effort unless there's someone needing it. AFAICT the purpose of `GET /vm/config` is debugging production workloads. Usage of it is very rare and quite probably no one will ever need remaining items.

**Comment by alindima** [comment]
We chatted about this some more in the team. I've opened a new issue and we'll keep it as low priority: https://github.com/firecracker-microvm/firecracker/issues/2943
