### ISSUE TITLE
Improve Guest Boot Time via Booting Compressed Kernel Images

### ISSUE THREAD

**Issue by alexandruag** [firecracker-microvm/firecracker#288]
Investigate whether decompressing an LZ4 compressed vmlinux.bin file on the fly, and using the resulting data with the current kernel image loader (which expects an uncompressed image), provides a meaningful boot time improvement.

**Comment by dianpopa** [comment]
The implementation of the initrd support in Firecracker shows us that using compressed images actually increases the boot time since there is some extra time added by the actual decompression of the kernel itself. The description of this [PR](https://github.com/firecracker-microvm/firecracker/pull/670) confirms this behavior when using bzImage compressed images.
