### ISSUE TITLE
Feedback ..... ability to load compressed kernels

### ISSUE THREAD

**Issue by bootrino** [firecracker-microvm/firecracker#2909]
FYI I gave firecracker a good try and got it working for most of my needs.

I abandoned the project however because firecracker cannot load compressed kernels.

Many of the operating systems I was to load, such as the Ubuntu cloud images, use compressed kernels.

I could not succeed in uncompressing the Ubuntu kernels using extract-vmlinux which ended my use of firecracker.

I understand compressed kernels would be slower too boot, but it should still be an option when there's no choice but to use a compressed kernel.

thanks!  and I do like the project.

**Comment by dianpopa** [comment]
Hi @bootrino 

There have been conversations in the past (see [this](https://github.com/firecracker-microvm/firecracker/issues/175) or [this](https://github.com/firecracker-microvm/firecracker/issues/288)) about adding support for compressed kernel images. However, we did not go further with that idea since, as you also mentioned, it is slower and there is always the possibility to decompress it and then pass it to Firecracker.

What exactly did not work for you in using extract-vmlinux? Maybe I can help with getting that to work for you.

**Comment by bootrino** [comment]
I don't recall.  Maybe you could give an example of how to decompress the kernel and then send it to firecracker, just to close the issue off in case anyone else comes looking.

**Comment by roypat** [comment]
Hi @bootrino,
as Diana mentioned, we do not plan to add the ability to load compressed kernels to firecracker. We also do not build compressed kernels (meaning there is no need for us to decompress them), so we have no experience troubleshooting problems with [extract-vmlinux](https://github.com/torvalds/linux/blob/master/scripts/extract-vmlinux), sorry :(. If you think you found a bug with the tool, maybe the linux mailing list would be a better place to ask for help?
