### ISSUE TITLE
[Feature Request] devcontainer/github codespaces support

### ISSUE THREAD

**Issue by lattice0** [firecracker-microvm/firecracker#3022]
# Feature Request

I work with GitHub codespaces on all my projects, and now they are opening support to non organizations, and it's even free at the moment, for a VM with 4 cores! Can I add a .devcontainer/devcontainer.json to this project?

Anyone will be able to compile/develop for firecracker on the browser using github codespaces

## Describe the desired solution

Have support for GitHub codespaces, so users can launch in GitHub codespaces or devcontainer locally

## Describe possible alternatives

there are no alternatives for devcontainer

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by mattschlebusch** [comment]
Hi @lattice0, thank you for the feature request. The team will discuss the request internally and provide feedback once we can determine and consider viability along with any potential maintenance overhead.

**Comment by sudanl0** [comment]
Hi @lattice0,

Thank you very much for opening this request and sorry for the delay.
It seems that we can build and test Firecracker by installing docker in codespace so this should not a blocker.
Unfortunately, we currently won't be able to maintain the devcontainer.json due to other high priority tasks and so I am closing this issue.
However, please feel free to post a draft PR with your changes if it can help other community members.
If we re-evaluate this position in the future, we will reopen this issue and let you know.
