### ISSUE TITLE
Slack channel invite link is no longer working

### ISSUE THREAD

**Issue by fertapric** [firecracker-microvm/firecracker#3191]
It seems the Slack channel invite link is no longer valid. When clicked, the Slack application says:

![E9DD05FD-F06C-4696-B740-69CEDFCDDEA0](https://user-images.githubusercontent.com/651203/196759886-d42541e8-a1fa-4883-a22f-f6c1ae6432c5.png)

**Comment by xmarcalx** [comment]
Hi @fertapric ,

Thanks for opening this issue and sorry for the inconvenient.
Which link did you use?

We have actually updated all the links in various PRs both in our codebase and website https://firecracker-microvm.github.io/ few weeks ago and they seems functional. 

Can you try to join using any link from the website and tell us if it works for you?

Thanks,
Marco

**Comment by fertapric** [comment]
Hi @xmarcalx,

This is the link: https://join.slack.com/t/firecracker-microvm/shared_invite/zt-oxbm7tqt-GLlze9zZ7sdRSDY6OnXXHg

If I click that link, it opens the Slack mobile app (iOS) and then it displays the error message I shared above.

**Comment by xmarcalx** [comment]
Hi @fertapric ,

yes that is an old link, if you use the newest one https://join.slack.com/t/firecracker-microvm/shared_invite/zt-1fecwrorm-x5URTlOzBR2fExTU2mWfug it will work.

Ok, I checked the root cause and even if we fixed the links a while ago here (https://github.com/firecracker-microvm/firecracker-microvm.github.io/pull/27), the deploy of the updated page failed so the link of some button was still not updated. I rerun the deploy (https://github.com/firecracker-microvm/firecracker-microvm.github.io/actions/runs/3189370239) and the page is up to live again with the correct link!

Thanks for reporting the issue and welcome to the community, you should be able to join us in slack now!

Regards,
Marco
