### ISSUE TITLE
Add Integration Tests for API Metrics

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#332]
Add unit tests for exercising error path; coverage drops a lot now that metrics are in effect for those error paths.

**Comment by luminitavoicu** [comment]
Related to #2901

**Comment by xmarcalx** [comment]
We are closing this issue because the code changed significantly since the issue was open and we have gradually included testing as per previous references. We restructured recently the metrics per devices, and we will may restructure metrics also for the APIs. At that time we will of course revamp testing for whichever new code implemented
