### ISSUE TITLE
Add Integration Tests for CPUID Related Functionality

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#342]
As part of these tests, we need to check the following:
- [x] the cpu topology for 1 vcpu/many vcpus
- [x] the cache topology for 1 vcpu/many vcpus
- [ ] the flags exposed with all the supported templates

I will add here whatever passes through my mind when I actually start working on this.

This issue is blocked by adding the ssh fixture. #78

**Comment by rpaul98** [comment]
Hi, @edengarza, @amaniduncker, and I are students at UT and are looking to contribute to an open source project for our virtualization class. We were wondering if we could get assigned to this issue.

Thanks!

**Comment by serban300** [comment]
Hi ! Sure. I have assigned you to the issue. Here the requirement is to extend [test_cpu_template](https://github.com/firecracker-microvm/firecracker/blob/3bf285c8f8a815149923c562dd7edaffcaf10c4e/tests/integration_tests/functional/test_cpu_features.py#L281) in order to test all the features that are set as part of the [C3 or T2 templates](https://github.com/firecracker-microvm/firecracker/tree/master/src/cpuid/src/template).

**Comment by gc-plp** [comment]
CPUID tests PR added here: https://github.com/firecracker-microvm/firecracker/pull/2623
