### ISSUE TITLE
[Feature Request] Any plan to contribute ratelimiter to crate.io

### ISSUE THREAD

**Issue by HowHsu** [firecracker-microvm/firecracker#3487]
# Feature Request

`I'm developing QoS for virtiofsd, and ratelimiter is used. Nowadays ratelimiter is used widely in other rust projects, does fire-cracker team has an plan to contribute it to crate.io so that developers can import it as a dependency rather than copy all the code everytime?`

Thanks,
Hao

**Comment by JonathanWoollett-Light** [comment]
Thank you for the question, we do not currently have plans for the [./src/rate_limiter](https://github.com/firecracker-microvm/firecracker/tree/main/src/rate_limiter). It is more likely we will adopt a generic rate limiter rather than publish our own in this case. So we wouldn't want to encourage depending on this implementation.

A popular generic rate limiter you may find useful is https://crates.io/crates/governor.

**Comment by HowHsu** [comment]
> Thank you for the question, we do not currently have plans for the [./src/rate_limiter](https://github.com/firecracker-microvm/firecracker/tree/main/src/rate_limiter). It is more likely we will adopt a generic rate limiter rather than publish our own in this case. So we wouldn't want to encourage depending on this implementation.
> 
> A popular generic rate limiter you may find useful is https://crates.io/crates/governor.

Thanks for quick reply, nice to know another option, I would look into it.

Thanks,
Hao

**Comment by HowHsu** [comment]
> Thank you for the question, we do not currently have plans for the [./src/rate_limiter](https://github.com/firecracker-microvm/firecracker/tree/main/src/rate_limiter). It is more likely we will adopt a generic rate limiter rather than publish our own in this case. So we wouldn't want to encourage depending on this implementation.
> 
> A popular generic rate limiter you may find useful is https://crates.io/crates/governor.

By the way, is Firecracker going to switch to use this crate?

**Comment by JonathanWoollett-Light** [comment]
> By the way, is Firecracker going to switch to use this crate?

We have no plans for this at the moment.

**Comment by xmarcalx** [comment]
Hi @HowHsu ,

thank you very much for opening this request and sorry for the delay.
As @JonathanWoollett-Light wrote, we currently do not have any plan to publish ratelimiter in crate.io because we do not have any strong reasons neither usecase or requests from others. 

For these reasons, I am closing this issue. If we will re-evaluate this position in the future, we will reopen this issue and let you know.

Thanks!
