### ISSUE TITLE
Update pre-commit hook to run git-secrets

### ISSUE THREAD

**Issue by raduweiss** [firecracker-microvm/firecracker#386]
Leverage https://github.com/awslabs/git-secrets to avoid committing secrets.

**Comment by Tobbeman** [comment]
Is this still of interest?

**Comment by roypat** [comment]
This is not something we can do in our CI, because by the time a commit with secrets reaches the CI, it is too late (as it will already have been published). The only thing we can do in the repository is to add `git-secrets` to our pre-commit hook (https://github.com/firecracker-microvm/firecracker/blob/main/pre-commit) so that contributors using this pre-commit hook get an additional layer of protection. I am marking this task of "add git-secrets to pre-commit hook" as a "good first issue"

**Comment by mistermuki** [comment]
I'm interested in this, is this still good to work on?

**Comment by roypat** [comment]
> I'm interested in this, is this still good to work on?

Hi @mistermuki, yes this is still good to work on! The task would be to update https://github.com/firecracker-microvm/firecracker/blob/main/pre-commit such that
 1. It checks if `git-secrets` is installed
    a. If no, print a warning, but do not fail the script
2. If yes, run git-secrets, and fail the script if git-secrets finds anything
