### ISSUE TITLE
Support getting Firecracker exit code from testing framework with jailer

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [firecracker-microvm/firecracker#4186]
Currently when running integration tests testing Firecracker inside the jailer it is unclear how to get the exit code of the process.

The solution should offer a simple mechanism to get the exit code.

## Additional context

https://github.com/firecracker-microvm/firecracker/pull/4178#discussion_r1363668082

**Comment by k-jingyang** [comment]
Hi, I was curious about this. Is the problem because jailer runs in its own process group (in daemon mode) and thus the calling process (e.g the testing framework) is unable to get the exit code?

**Comment by pb8o** [comment]
Yes, the integration tests and the firecracker process don't have a parent->child relationship and thus we cannot use any of the `wait`  system calls. 

A cheap mechanism would be to write the exit code in the logs as  debug message, and parse it in the logs. Would not cover all cases but would give us something.

**Comment by k-jingyang** [comment]
@pb8o I tried to take a stab at this. The draft PR #4220 still contains a few logging statements. But I'ld like to know if I'm on the right track. Instead of logging the exit code, I'm saving the exit code into a file (similar to the PID solution).

**Comment by pb8o** [comment]
Thanks for taking a look! I see that your PR modifies the jailer so that it waits for the process to finish, which means we will have the jailer running for the whole duration of the guest workload. I think that's too much overhead to just get the exit code. 

I would look into other approaches. For example, in the devctr we use `tini`, a replacement `init` inside the Docker session. AFAICS, it is the parent of all the Firecracker processes. It looks like `tini` can print the exit status of a child if we give the `-v` option, so it would be interesting to see if we can do something like:

- enable `-v` in `tini`
- in the `Microvm::kill()` method, search for the PID in the tini logs (don't know how to redirect this, but maybe there's a way), and look for the exit code.

This would without having to change the jailer or Firecracker.

**Comment by k-jingyang** [comment]
> Thanks for taking a look! I see that your PR modifies the jailer so that it waits for the process to finish, which means we will have the jailer running for the whole duration of the guest workload. I think that's too much overhead to just get the exit code.
> 
> I would look into other approaches. For example, in the devctr we use `tini`, a replacement `init` inside the Docker session. AFAICS, it is the parent of all the Firecracker processes. It looks like `tini` can print the exit status of a child if we give the `-v` option, so it would be interesting to see if we can do something like:
> 
> * enable `-v` in `tini`
> * in the `Microvm::kill()` method, search for the PID in the tini logs (don't know how to redirect this, but maybe there's a way), and look for the exit code.
> 
> This would without having to change the jailer or Firecracker.
> 
> The other approach is to just print the exit status in the Firecracker logs, which should be pretty simple too.
> 
> Another approach would be to trace the exit status, but would require adding some dependencies.
> 
> In general the solution should be simple. If it is too invasive we can live without this functionality since we don't have a strong need for it yet.

Thanks for the feedback. Let me dig into it again and get back!
