### ISSUE TITLE
[Feature Request] Would firecracker support  linux32, multiboot, multiboot2?

### ISSUE THREAD

**Issue by RuixiangJiang** [firecracker-microvm/firecracker#4304]
# Feature Request

I am in a team whose product only supports linux32 and multiboot. I tried to run it on Firecracker but it failed due to the ELF kernel image loading. Could firecracker support linux32 and multiboot?
Thanks.

## Checks

- [x] Have you searched the Firecracker Issues database for similar requests?
- [x] Have you read all the existing relevant Firecracker documentation?
- [x] Have you read and understood Firecracker's core tenets?

**Comment by kalyazin** [comment]
HI @RuixiangJiang . Thanks for contacting us. linux32/multiboot has never been considered during Firecracker development as we haven't had a business use case for that. The code has been written with an assumption it would not need to be supported.
Is there something that makes you look into linux32/multiboot specifically?

**Comment by RuixiangJiang** [comment]
您好，我现在没有时间回复您，请稍等！

**Comment by sudanl0** [comment]
Hi @RuixiangJiang ,
As mentioned earlier linux32/multiboot has never been considered during Firecracker development as we haven't had a business use case for that.
Closing this issue since we don't plan to work on this. Please feel free to reach out to us or reopen if you have any questions or updates.
Thanks!

**Comment by RuixiangJiang** [comment]
您好，我现在没有时间回复您，请稍等！
