### ISSUE TITLE
[Bug] Build fails: unresolved imports rustix::time::Itimerspec, rustix::time::TimerfdClockId

### ISSUE THREAD

**Issue by yurivict** [firecracker-microvm/firecracker#4344]
```
error[E0432]: unresolved imports `rustix::time::Itimerspec`, `rustix::time::TimerfdClockId`
  --> /usr/ports/emulators/firecracker/work/firecracker-1.6.0/cargo-crates/timerfd-1.5.0/src/lib.rs:51:20
   |
51 | use rustix::time::{Itimerspec, TimerfdClockId};
   |                    ^^^^^^^^^^  ^^^^^^^^^^^^^^ no `TimerfdClockId` in `time`
   |                    |
   |                    no `Itimerspec` in `time`
   |                    help: a similar name exists in the module: `Timespec`

error[E0432]: unresolved imports `rustix::time::TimerfdFlags`, `rustix::time::TimerfdTimerFlags`
   --> /usr/ports/emulators/firecracker/work/firecracker-1.6.0/cargo-crates/timerfd-1.5.0/src/lib.rs:128:20
    |
128 | use rustix::time::{TimerfdFlags, TimerfdTimerFlags};
    |                    ^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^ no `TimerfdTimerFlags` in `time`
    |                    |
    |                    no `TimerfdFlags` in `time`

error[E0432]: unresolved import `rustix::time::Itimerspec`
 --> /usr/ports/emulators/firecracker/work/firecracker-1.6.0/cargo-crates/timerfd-1.5.0/src/structs.rs:3:20
  |
3 | use rustix::time::{Itimerspec, Timespec};
  |                    ^^^^^^^^^^
  |                    |
  |                    no `Itimerspec` in `time`
  |                    help: a similar name exists in the module: `Timespec`
  |
  = help: consider importing this unresolved item through its public re-export instead:
          Itimerspec

error[E0425]: cannot find function `timerfd_create` in module `rustix::time`
   --> /usr/ports/emulators/firecracker/work/firecracker-1.6.0/cargo-crates/timerfd-1.5.0/src/lib.rs:187:32
    |
187 |         let fd = rustix::time::timerfd_create(clock, flags)?;
    |                                ^^^^^^^^^^^^^^ not found in `rustix::time`

error[E0425]: cannot find function `timerfd_settime` in module `rustix::time`
   --> /usr/ports/emulators/firecracker/work/firecracker-1.6.0/cargo-crates/timerfd-1.5.0/src/lib.rs:208:33
    |
208 |         let old = rustix::time::timerfd_settime(&self.0, flags, &new)
    |                                 ^^^^^^^^^^^^^^^ not found in `rustix::time`

error[E0425]: cannot find function `timerfd_gettime` in module `rustix::time`
   --> /usr/ports/emulators/firecracker/work/firecracker-1.6.0/cargo-crates/timerfd-1.5.0/src/lib.rs:215:35
    |
215 |         let state = rustix::time::timerfd_gettime(&self.0)
    |                                   ^^^^^^^^^^^^^^^ not found in `rustix::time`

```

timerfd-1.5.0
rustix-0.37.27
rustix-0.38.28

rust-1.74.1
FreeBSD 14.0 STABLE

**Comment by sudanl0** [comment]
Hi @yurivict,
FreeBSD is not officially by Firecracker, please find the list of supported platforms here: https://github.com/firecracker-microvm/firecracker?tab=readme-ov-file#tested-platforms.

However, I don't think the issue is with FreeBSD and my guess is that the build was tried without the docker container so your system is missing required dependencies to build Firecracker (please correct me if I am wrong).

Could you please try building Firecracker on a linux platform and use [Bug report template](https://github.com/firecracker-microvm/firecracker/issues/new?assignees=&labels=Quality%3A+Bug&projects=&template=bug_report.md&title=%5BBug%5D+Title) to fill the information related to what exact command were run. The recommended way to build Firecracker is 
```bash
firecracker_src/tools/devtool build
```

You can also have a look at the [Getting a Firecracker Binary](https://github.com/firecracker-microvm/firecracker/blob/main/docs/getting-started.md#getting-a-firecracker-binary) section which has steps to build Firecracker.

**Comment by roypat** [comment]
Hi @yurivict,
The issue you're seeing is not in Firecracker, but rather in rustix. I assume that when building on FreeBSD, the `rustix` crate does not expose the timerfd APIs (probably because they're linux specific - if they're not, maybe you could raise an issue on the rustix repository about supporting these APIs on FreeBSD?). You can try cross-compiling Firecracker for a linux target by passing `--target x86_64-unknown-linux-musl` (or similar) to your `cargo build` invocation. However, either way, Firecracker will not run on a FreeBSD host, as it is KVM based.
