### ISSUE TITLE
MMDS - Return 204 instead of 201 on PUT requests

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#528]
We don't send a body along with the status code in case of success, so we should use the status code 204 (NoContent). Currently the PUT /mmds request returns a  response with a null body and the status code 201.

**Comment by fristonio** [comment]
Hey, @andreeaflorescu if I am correct then this has been resolved since PUT request to `/mmds` returns a status code of 204(NoContent).
Or are we talking about the case when `is_initialized` returns false?
Here https://github.com/firecracker-microvm/firecracker/blob/master/api_server/src/http_service.rs#L498

**Comment by andreeaflorescu** [comment]
Hey, we should always return 204 because we do not returning any content even when the MMDS store is not initialized. We should remove the is_initialized for this.

**Comment by fristonio** [comment]
Ok thanks, I will send a PR soon fixing this. :)
