### ISSUE TITLE
CI: automatically check against presence of license header

### ISSUE THREAD

**Issue by dianpopa** [firecracker-microvm/firecracker#570]
Ensure that every file in a pull request has a header referring to the repository license file.

**Comment by christopherdiehl** [comment]
Any preference in how this would be accomplished and whether the Chromium license should be validated as well? 

My first thought would be to iterate through all the files and validate the license in .py and .rs files using something like this:

```
COPYRIGHT = "Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved."
LICENSE = "SPDX-License-Identifier: Apache-2.0"
def validate_license(filename):
    with open(filename) as f:
        copy = f.readline()
        license = f.readline()
        # no equality checks so this works with .py and .rs files
        return COPYRIGHT in copy and LICENSE in license 

for subdir, dirs, files in os.walk(os.getcwd()):
    for file in files:
        if file.endswith(('.rs','.py')) and not validate_license(os.path.join(subdir,file)):
            print('Test failed for file ' + file)
```
After looking through the codebase I think it makes sense to place this test in /tests/integration_tests/test_style.py. 

If helpful I can work on this and submit a PR.

**Comment by raduweiss** [comment]
Hey, thanks for helping out! It's definitely helpful.

There's a couple of edge cases here:

- Some crosvm files we have [not modified at all](https://github.com/firecracker-microvm/firecracker/blob/master/sys_util/src/eventfd.rs) need the original Chromium OS license.
- There's a few shell scripts around here, they need a license too. You can take a look at the PR that adds all the license headers to see all the kinds of files that received them.

As for where to place it, I suggest you create a new file, since this is a new kind of check, e.g., `test_license.py`.

Thanks!

**Comment by christopherdiehl** [comment]
@raduweiss Please let me know what you think and if any changes to the PR are needed!

**Comment by dianpopa** [comment]
#703 was merged. Closing this as there is not anything left to solve here.
