### ISSUE TITLE
Enforce performance & code coverage are not decreasing 

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#611]
Enforce that PRs are not lowering the code coverage, increasing the memory usage, increasing the boot-time and the other SLAs. For this task we should update all these values on all merges and check against those values when testing PRs instead of static values.

**Comment by raduweiss** [comment]
There's currently a manual mandatory check here for coverage: if the gap between actual code coverage and the threshold is greater than 0.01, than you need update the code coverage manually or the PR check will fail. This can be automated, but it's not urgent.

For other metrics beyond code coverage, we also need to stick to a manual bar for now, since there's noise in the data, and automating it means moving to a more complicated system that samples several runs.

**Comment by andreeaflorescu** [comment]
@raduweiss I have increased the priority to medium. It is very important to know if PRs increase boottime and memory overhead. We need a mechanism to ensure that. I am not convinced that the variance is a good thing either, maybe we should also take a look into the "whys" before fixing this issue.

**Comment by raduweiss** [comment]
Well, I selected the `low` part factoring int the cost ... it will take a bit of work to get this to something better than what we have now. But I guess wether we factor in the cost or not in this label is not defined. Either label works for now.

**Comment by alindima** [comment]
We now have boot time performance tests that run as part of the CI, as well as a memory monitor that checks that the VMM added memory stays below 5mib, as well as a test that checks coverage stays above a limit
