### ISSUE TITLE
Remove pnet dependency

### ISSUE THREAD

**Issue by andreeaflorescu** [firecracker-microvm/firecracker#612]
This dependency adds ~15 external dependencies and it is only used in tests.
The tests that use pnet can be refactored to use the Firecracker network stack, `dumbo`.
Alex (@alexandruag) is the right person to bug about this.

**Comment by SecurityInsanity** [comment]
Started taking a look at this locally, but it seems `dumbo` doesn't yet have anything to replace the UDP Packets that are currently parsed in: `net_util/src/tap.rs`. A simple grep for UDP is returning nil:

```
$ rg -i 'udp' .
$ echo $?
1
$
```

Grepping through the other parts of the repo isn't showing a smoking gun for a replacement. Anything I'm missing here, or should I start implementing a UdpPacket for dumbo as part of this work?

**Comment by andreeaflorescu** [comment]
@alexandruag had an idea about how this could be achieved, you can ping him on Slack for details, but there might be some delays in communication as he is not currently in the office.

**Comment by SecurityInsanity** [comment]
No worries, I can wait til after re:Invent (which I assume is where he is at), and ping him then. Thanks!

**Comment by alexandruag** [comment]
It would be very cool to also have some UDP datagram support in `dumbo`, even if it's just a bare-bones implementation to begin with. If that's available, we could replace `pnet` raw packet send/receive functionality with the standard Rust `UdpSocket` implementation. This complicates things a bit for `test_read()`, because it's likely that an ARP request (which requires a reply) will be sent before the actual datagram.

There are a couple of other solutions, which don't involve UDP datagrams, for example using TCP segments, or raw sockets via `libc`, but I think they're more awkward. Also, as you might have noticed, I like the `UdpDatagram` name more than `UdpPacket`, but it's entirely your choice if you implement it :grin:

**Comment by SecurityInsanity** [comment]
Thanks for the thoughts! I think I'll start moving forward with UDP Datagrams for now, and see where that takes me!

**Comment by alexandruag** [comment]
Hi @SecurityInsanity, did you manage to explore things a bit?

**Comment by SecurityInsanity** [comment]
Ah sorry! This completely fell off my radar after some personal things :disappointed: . If I remember correctly I was pretty close, I can check out my repo this weekend, and give an update. Though I imagine it'll probably need to be rebased at this point.

**Comment by SecurityInsanity** [comment]
Looking at my local repo it seems I misremembered where the actual code was at, and unfortunately, I don't think I have the free time to take it anywhere useful right now.

I think sharing what I was planning on doing, might be useful since that's what it seems I actually left notes on:

   1. Create `UdpDatagram` struct that contains (`source_port`, `dest_port`, `length`, `checksum`, and `data`) (The IPv4 Address are given to use by `UdpSocket`).
   2. Implement `UdpDatagram` struct with some tests to ensure checksum is computed right (and it enforces the max length of a `UdpDatagram` (remember this isn't `65,537` since we have the 20 byte IPv4 header).
   3. Most of the tap class contains references to `EthernetPacket`/`MutableEthernetPacket`, and `Ipv4Packet`/`MutableIpv4Packet`, this should be able to be replaced entirely by `UdpSocket` in the standard library. There will be some points where we'll miss an "early-exit"  (e.g. no way to do: `packet.get_ethertype() != EtherTypes::Ipv4` that I know of from UdpSocket). BUT! tests should be functionally equivalent.

**Comment by alexandruag** [comment]
Thanks a lot for the outline, and sorry for not getting back with a reply for so long :( I'll try to comment on what you've described as soon as I can refocus a bit on this part :D

**Comment by shakram02** [comment]
Hey, I'm new to `firecracker :wave: ` and this is my first attempt to contribute 
I'll be working on this issue, Can you please tell me if the outline commented above is still valid?

I opened a pull request #1238 the will contain my work on the issue.

**Comment by shakram02** [comment]
SecurityInsanity thank you for the guideline, I would've definitely missed the max packet length part

The only missing part now is to find a way to remove the `pnet::datalink` which is used to find a network interface, get a `tx` &`rx`channels for communications. Any suggestions?

**Comment by shakram02** [comment]
thank you @SecurityInsanity  for the guidelines, I would've surely missed the length check.

I'm confused about something, I completed the UDP parsing implementation, but I'm not able to test it with `UdpSocket`, I'm not really sure how to send packets to a TAP device but I use the TAP's IP and a random port number. (@alexandruag) 

I do get packets from other source (chrome cast service or something and I'm able to parse their message correctly), not sure what I'm failing at, any suggestions? (I'm a total OS newbie)
