### ISSUE TITLE
Packer plugin

### ISSUE THREAD

**Issue by mcandre** [firecracker-microvm/firecracker#667]
Would like to see fiirecracker compete in the Vagrant space!

**Comment by raduweiss** [comment]
Not sure what the ask here is (might be just me since I'm not very familiar with Vagrant) Can you be more specific?

**Comment by Pryz** [comment]
I guess here the idea is to be able to use Firecracker with Vagrant ? So create a Vagrant provider like the libvirt one (https://github.com/vagrant-libvirt/vagrant-libvirt).

**Comment by raduweiss** [comment]
Well, our mission with Firecracker is to enable secure, multi-tenant, minimal-overhead execution of container and function workloads. We want to keep the focus on those kinds of use cases. Another thing is that client-side VMs probably require a lot more features than what we will ever have in Firecracker (since we'll only add features that are required for container and function workloads).

That being said, if Firecracker as it is can work with Vagrant ... well, we take pull requests 😄.

@mcandre if this answers your question, please go ahead and close the issue.

**Comment by alexandruag** [comment]
Closing this due to apparent inactivity. Please feel free to reopen at any time.
