### ISSUE TITLE
RISC-V support

### ISSUE THREAD

**Issue by JoelEllis** [firecracker-microvm/firecracker#752]
Run Firecracker on RISC-V CPUs. 
This is probably a good idea as the RISC-V project is accelerating in adoption and companies like SiFive are allowing people and companies to create extremely custom CPUs for whatever task they need. 

> RISC-V  is free and open-source and can be used royalty-free for any purpose.
https://en.m.wikipedia.org/wiki/RISC-V

**Comment by raduweiss** [comment]
Ok, this is something to think about 😄. Assuming someone in the community doesn't just want to contribute this [*], the question becomes when is the right time to prioritize this:

1. How mature / security tested is RISC-V virtualization? Our mission with Firecracker is to provide isolation that meets the multi-tenant scenario security bar, and the hardware implementation is a part of that.

2. Is there any demand for running container / serverless function type workloads on RISC-V platforms?

[*] If you do, get in touch with @dianpopa since I think that as part of her ARM she will also more or less modularize the way we include CPU support in the code base.

**Comment by derpmarine168** [comment]
some info about the maturity of virtualisation on RISC-V in this PDF from 2017:
https://content.riscv.org/wp-content/uploads/2017/12/Tue0942-riscv-hypervisor-waterman.pdf

I have no idea about demand, but it’s a garuntee that someone, somewhere wants to do it, and more people will want to as RISC-V becomes more mainstream. For quite a lot of people, they don’t care what the architechture is, they just want it to be fast. It’s getting there quickly (Nvidia is using it as the glue inside its future graphics cards, plus it is backed by Google, Samsung, Qualcomm, and other organizations.)

I’ve got no experience in virtualisation and things like that, (the most I’ve done is used virtualbox) but I’ve been doing Rust for a bit now. I have no idea how I would even start to contribute code-wise on this. If you can think how I’d help, or are willing to teach me, I’d be happy to.

**Comment by raduweiss** [comment]
Personally I see nothing wrong with having RISC-V this as an optional feature, but at least from the maintainers side, we set our priorities based on clear user demand / use cases. So for now it's going to be in the "contributions welcome" category.

As for learning virtualization to contribute this, we can definitely give you feedback once you're on your way, but I'm afraid you'd be starting at the deep end o the already deep virtualization pool here 🙂.

**Comment by raduweiss** [comment]
@JoelEllis, we've looked at this again as part of our 2020 Roadmap exercise, and in the end we thought this is best done in rust-vmm, not Firecracker (and Firecracker can then consume it from there in the future).

Therefor, I'll be closing this now. Feel free to re-open it if you want to continue the conversation :)
