### ISSUE TITLE
add vsock vhost fd to vsock config

### ISSUE THREAD

**Issue by bergwolf** [firecracker-microvm/firecracker#782]
Right now the vmm vsock device only contains guest cid (https://github.com/firecracker-microvm/firecracker/blob/master/vmm/src/vmm_config/vsock.rs#L11). And it assumes the manager that launches FC can allocate the guest cid properly. However, in order to ensure the cid generated by the manager is not reused by others, one must keep the vhost vsock device open fd otherwise the kernel will close it and free the occupied guest cid. 

So can we modify the FC vsock device config API to include a vsock_vhostfd option? When it is zero, it works just like current version. And when it is non-zero, FC server should use the passed in fd for the vhost vsock device rather than opening a new one.
```
diff --git a/vmm/src/vmm_config/vsock.rs b/vmm/src/vmm_config/vsock.rs
index cd58371..a83585e 100644
--- a/vmm/src/vmm_config/vsock.rs
+++ b/vmm/src/vmm_config/vsock.rs
@@ -11,6 +11,9 @@ use std::result;
 pub struct VsockDeviceConfig {
     /// ID of the vsock device.
     pub id: String,
+    /// The vhost-vsock device open fd. 0 means unassigned, and we should
+    /// open the vsock vhost device internally.
+    pub vsock_vhostfd: u32,
     /// A 32-bit Context Identifier (CID) used to identify the guest.
     pub guest_cid: u32,
 }
```

The same model is in-used by QEMU as well such that it allows users to pass an open vhost vsock fd along with the vsock device.

**Comment by sboeuf** [comment]
@bergwolf definitely, we need a way to send OOB the file descriptor so that the caller don't have to close it before it's reopened by FC, which is racy. I'm not sure if there's a simple way to do that through REST API though...

**Comment by bergwolf** [comment]
@sboeuf The proposed change would allow vsock cold plug in which case we can pass the open fds when launching FC. Then the REST API is just used to tell FC which vhost fds are passed. It's the same workflow Kata uses with QEMU right now.

**Comment by sboeuf** [comment]
Ah yes, the FC process would be spawned inheriting the open fds. And a simple ID would identify later through the REST API which fd the caller wants to use, right? Just trying to make sure I'm clear on this here!

**Comment by bergwolf** [comment]
@sboeuf Yes ;)

**Comment by dhrgit** [comment]
There are a few issues to consider here, since:
- Security-wise, Firecracker is meant to be run in isolation, via the `jailer` binary
- The jail restricts access to unneeded and/or unknown resources. As such, the `jailer` closes all fds it isn't aware of, prior to `exec`-ing into `firecracker`. The fds that make it to `firecracker` are:
  - `0`, `1`, and `2` (`dup`-ed to `/dev/null` when daemonized)
  - `3` - `/dev/kvm`
  - `4` - the API socket

A solution, that comes to mind, would be to rely on Firecracker to report the CID reservation status. I.e. have the API call fail if the requested CID cannot be acquired. Would that work for you?

Also, I understand you are running `firecracker` directly, without jailing it. Indeed, the vsock experimental feature is not currently working with the jailer (because the chroot jail doesn't contain `/dev/vhost-vsock`), but that is easily fixable. Aside from that, though, is there any other reason for you not to use the jailer?

**Comment by bergwolf** [comment]
> have the API call fail if the requested CID cannot be acquired.

Yeah, I understand the security reason of jailing. The solution cannot close the race window but I think we can live with it. We can move the cid allocation to right before calling the FC API and have a retry mechanism there. @sboeuf WDTY?

> I understand you are running firecracker directly, without jailing it

I don't think we are avoiding the jailer on purpose. We are adding FC support to kata containers in steps and jailer is definitely something we want to look into next.

**Comment by dhrgit** [comment]
> The solution cannot close the race window but I think we can live with it. 
I'm not sure I understand where the race would occur. From your point of view, you'd just be replacing the ioctl call with a firecracker API call. I was suggesting you don't open `/dev/vhost-vsock` yourself, but rely on Firecracker to do it (upon `PUT /vsocks`) and manage the fd internally.

**Comment by sboeuf** [comment]
@dhrgit 
>I'm not sure I understand where the race would occur. From your point of view, you'd just be replacing the ioctl call with a firecracker API call. I was suggesting you don't open /dev/vhost-vsock yourself, but rely on Firecracker to do it (upon PUT /vsocks) and manage the fd internally.

Yes, different approach, but it would definitely work :+1:

About @bergwolf comments:
>I don't think we are avoiding the jailer on purpose. We are adding FC support to kata containers in steps and jailer is definitely something we want to look into next.

I agree we haven't avoided it on purpose. Just easier to start without it. Any comments on this @mcastelino @egernst?

**Comment by bergwolf** [comment]
> I'm not sure I understand where the race would occur. From your point of view, you'd just be replacing the ioctl call with a firecracker API call. I was suggesting you don't open /dev/vhost-vsock yourself, but rely on Firecracker to do it (upon PUT /vsocks) and manage the fd internally.

Opening `/dev/vhost-vsock` is how we close the race window right now. The kernel can make sure the open fd holds the cid for both the CID number allocator process and the QEMU process. And the open fd is passed around between the two.

For the new FC vsock API, we still need to close the `/dev/vhost-vsock` fd before sending it to FC and at that point there might be someone else grabbing the same CID before FC.

It is not a big issue though. We can add a retry mechanism when calling the FC vsock API. Ideally the race won't happen and we can retry the same API with a different CID when it does.

**Comment by dhrgit** [comment]
> For the new FC vsock API, we still need to close the /dev/vhost-vsock fd before sending it to FC and at that point there might be someone else grabbing the same CID before FC.

But why do you need to open `/dev/vhost-vsock` in the first place?

The way I see it, you have two options to acquire the CID:
1. via vhost / host kernel: open `/dev/vhost-vsock` and retry the `VHOST_VSOCK_SET_GUEST_CID` ioctl, until you acquire a CID, then pass that CID to Firecracker. As I understand, this is your current approach. Or
2. via Firecracker: don't touch `/dev/vhost-vsock` at all, and just retry the `PUT /vsocks` API call, until Firecracker reports a successful CID acquisition.

I was suggesting the latter, since it's race-free. Is there anything I'm missing?

**Comment by dhrgit** [comment]
Summing up, the approach here for Firecracker to reserve the CID on `PUT /vsocks`, and report the status back to the caller. I.e. fail if the CID couldn't be reserved, succeed if the reservation went through.

**Comment by dhrgit** [comment]
Closing this as not applicable to the ongoing work for stable vsock.
