### ISSUE TITLE
MMDS: Support Callout Mechanism for Some/All Paths

### ISSUE THREAD

**Issue by rgooch** [firecracker-microvm/firecracker#833]
I would like to to be able to call out to external code to service some or all paths for the metadata service. This is useful for content that is created on-the-fly.

If all paths are serviced by external code, then a possible implementation would be to specify a Unix socket which the MMDS will connect to and proxy traffic.

If only some paths are serviced by external code, then a more intelligent HTTP proxy could be used, which forwards requests to a Unix socket.

**Comment by alexandruag** [comment]
Hi,

If all paths are serviced by external code, isn't it more straightforward to forgo the MMDS altogether, and send requests directly to the custom handler, which can listen on some <address:port> associated with a TAP interface attached to the VM?

If only some paths are used, it gets trickier. However, it seems like once a subset of the requests are handled externally, you can move pretty much all of them there, because the boilerplate functionality is already implemented.

**Comment by rgooch** [comment]
Having all the requests forwarded works fine for me. The reason I suggested the more complex per-path forwarding is in case you want MMDS to always provide some paths (i.e. so a guest can always probe to check that it's a Firecracker VM).

Ultimately, I'm looking to leverage the traffic capturing capabilities of MMDS, as that would allow me to bypass some of the tricks I have to do to capture traffic to/from the metadata service. See the "Networking Implementation" section in Appendix 1: https://bit.ly/SmallStack

**Comment by rgooch** [comment]
Hi. Any updates on this? On further thinking, it think it would be valuable to capture all traffic to `169.254.0.0/16`. This would allow for a more secure communication between the VM and metadata service (and other services), without needing to set up ebtables and iptables filtering rules to protect against MAC and IP spoofing attacks from neighbouring VMs. Sensitive data such as keys/tokens require a secure communication channel.

**Comment by alexandruag** [comment]
Hi, apologies for the very late reply :( So, just to make sure I understand correctly, you'd like to make use of the Firecracker MMDS capturing packets to proxy (some) guest requests intercepted like that to an Unix Domain Socket (for example), because you want to turn what would otherwise be `<HTTP/TCP/IP>` connection that has to bounce around on the host into a `<Something/Unix Domain Socket>` which is easier to manage.

One high-level solution is: the MMDS replies normally to requests for keys which are present in its data store, but forwards any other request to an UDS, waits for a response, and then sends that back to the guest.

This would be a pretty neat feature, but the current static MMDS is sufficient for our use cases. Moreover, using the above functionality does tend to muddle the security model a bit, and makes it harder to reason about the resource overhead associated with each microVM. It's not something we see on our roadmap anytime soon, but we're not averse to an external contribution. However, a more in-depth discussion would be nice before anyone attempts anything like that.

Regarding you last message, the Firecracker guest<->MMDS communication happens entirely within each individual process, so we don't have to worry about spoofing and the like. In-Firecracker blocking of certain traffic from ever accidentally leaving/entering the guest might be a valuable security proposition for some use cases, but it kinda feels like a separate discussion. 

One thing which does appear on our roadmap is stabilizing the Vsock feature (which has the experimental status right now). It does not solve everything right out of the box, but would it work as more secure communication channel between VMs and different host-based services for your use case?

**Comment by rgooch** [comment]
To your first question: no, as I've thought more about this I'd rather drop the Firecracker MMDS, since using MMDS to service some requests and not others seems complex, confusing and ugly.

So, my current thinking is that I just want a secure channel between the host and the VM, which appears to the VM as anything on 169.254.0.0/16. I want to keep backwards compatibility with the existing metadata service, which is why Vsocks aren't really the right match, I think.

**Comment by alexandruag** [comment]
As things are right now, if something starts off as network traffic in the guest, it will invariably come out as network traffic on the corresponding host TAP interface (unless the MMDS gobbles it up). Vsock was supposed to be the simpler, more secure guest<->host channel alternative, but it does not cover use cases such as yours. It seems like you're looking for something in the device model that feeds guest network traffic into/from an UDS (for example) via some sort of transformation. Unfortunately that's not on our roadmap, but we're open to discussing more specific proposals and/or external contributions.

**Comment by raduweiss** [comment]
@rgooch. We've looked at this again as part of our 2020 Roadmap exercise, but in the end, beyond the arguments above, it looks like this can be achieved via the upcoming vsock mechanism.

Therefor, I'll be closing this now. Feel free to re-open if you want to continue the conversation :)

**Comment by rgooch** [comment]
@raduweiss: Using vsocks requires applications to be change from using standard HTTP GET requests to 169.254.169.254 to using a totally different API. I'm seeking to secure communications with the metadata service, I'm not seeking to build a different communications channel.
