### ISSUE TITLE
Switch to Rust 2018 edition

### ISSUE THREAD

**Issue by saschagrunert** [firecracker-microvm/firecracker#839]
Hey :hand: is it indented to stick to Rust 2015 for some compatibility reasons or would it be worth changing to the latest 2018 edition of Rust?

**Comment by andreeaflorescu** [comment]
I say we should change it to 2018 edition but some other people should chime in if they have any concerns about this.

**Comment by raduweiss** [comment]
+1 for keeping our dependencies fresh across the board.

**Comment by damienstanton** [comment]
I am happy to take a crack at this, seems like an easy first issue.

**Comment by saschagrunert** [comment]
> I am happy to take a crack at this, seems like an easy first issue.

Alright, feel free to take over this part. 👍

**Comment by damienstanton** [comment]
@saschagrunert if possible, can you please assign this to me? I want to make sure it doesn't drop off my radar.

**Comment by saschagrunert** [comment]
@damienstanton sorry, but I am not allowed to do so and there is not bot around for those tasks.

**Comment by damienstanton** [comment]
Hey @raduweiss @alexandruag - I finally found some time to come back to this and have opened the relevant PR. Let me know if I should do anything else on my end from here.

**Comment by andreeaflorescu** [comment]
Hey @damienstanton there are a quite a few improvements from Rust 2015 to Rust 2018. I was picturing this issue to also include changes to firecracker code so that improvements are used.

Some examples of things I would expect to see change when switching to 2018:
- remove the `'static` lifetime definition where appropriate. Details here: https://doc.rust-lang.org/edition-guide/rust-2018/ownership-and-lifetimes/simpler-lifetimes-in-static-and-const.html
- remove the many unneeded `extern crate`. Details here: https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html#no-more-extern-crate
- remove empty mod.rs files. I haven't checked all of them but devices/src/legacy/mod.rs looks like a good one to get rid of. There might be others. Details here: https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html#no-more-modrs

There are also other goodies that we can take advantage of since we are switching to Edition 2018. This needs to be better investigated.

**Comment by damienstanton** [comment]
That sounds great - thank you for the feedback. I like the idea of making it a more comprehensive update 🙂

I'll go through the links you've provided and the edition guide at large, and see where other refactoring ideas pop up.

**Comment by damienstanton** [comment]
@andreeaflorescu I've taken a dive deeper into your suggested refactors in my spare time this week, and am tracking progress in the open PR: #1105. I think this is closer in spirit to what you suggested as I went through each crate and made updates based on the 2018 idioms.

The most recent CI failure is unlike others I have seen, it looks like the Docker host itself has died:
```
[Firecracker devtool] Error accessing Docker. Please make sure the Docker daemon is running 
and that you are part of the docker group. 
For more information, see https://docs.docker.com/install/linux/linux-postinstall/
```
I'll have access to a physical machine later and see if I can get the integration tests to pass locally.

**Comment by andreeaflorescu** [comment]
@damienstanton thanks for the thorough investigation! I'll take a look at it tomorrow. I'll also investigate the CI issue.

**Comment by damienstanton** [comment]
I think I may have found an upstream error in the `pnet` crate when running the integration suite on the firecracker `net_util` crate:
```
error[E0599]: no method named `to_primitive_values` found for type `pnet_base::MacAddr` in the current scope
   --> /tmp/firecracker_test_session/firecracker_binaries/test/x86_64-unknown-linux-musl/debug/build/pnet_packet-7c18985330f16ec5/out/ethernet.rs:442:24
    |
442 |         let vals = val.to_primitive_values();
```

I'll dig some more. But so far looking pretty close to having a successful across-the-board integration build done.

**Comment by damienstanton** [comment]
Update: I am back after some time off and am restarting this effort from the current master, including the recent push to Rust 1.3.5. I will open a new PR referencing this ticket when ready.

@andreeaflorescu @dianpopa thanks for your patience! :pray:

**Comment by acatangiu** [comment]
@damienstanton @saschagrunert do you still plan to contribute here?

**Comment by saschagrunert** [comment]
> @damienstanton @saschagrunert do you still plan to contribute here?

I was waiting for @damienstanton to take action :)

**Comment by damienstanton** [comment]
Hi @acatangiu @saschagrunert thanks for the ping, I had forgotten about this issue since nearly a year (wow!) has passed. I'm happy to take it up again.
