### ISSUE TITLE
Remove rand dependency

### ISSUE THREAD

**Issue by acipu-aws** [firecracker-microvm/firecracker#884]
There is no obvious reason why firecracker needs access to either the getrandom syscall or to /dev/urandom. For low-entropy systems this can cause problems if the getrandom syscall blocks and /dev/urandom is not available.

Some code inspection shows that the rand dependency is introduced by clap.

**Comment by acipu-aws** [comment]
@dianpopa any updates on this issue?

**Comment by dianpopa** [comment]
Hi,

What I discovered here this is that Firecracker needs rand since HashMap in rust are based on randomness. Take a look at https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/rand.rs#L4.
 You can see that it will call [fill_bytes](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/rand.rs#L65):
```
pub fn fill_bytes(v: &mut [u8]) {
        // getrandom_fill_bytes here can fail if getrandom() returns EAGAIN,
        // meaning it would have blocked because the non-blocking pool (urandom)
        // has not initialized in the kernel yet due to a lack of entropy. The
        // fallback we do here is to avoid blocking applications which could
        // depend on this call without ever knowing they do and don't have a
        // work around. The PRNG of /dev/urandom will still be used but over a
        // possibly predictable entropy pool.
        if getrandom_fill_bytes(v) {
            return;
        }

        // getrandom failed because it is permanently or temporarily (because
        // of missing entropy) unavailable. Open /dev/urandom, read from it,
        // and close it again.
        let mut file = File::open("/dev/urandom").expect("failed to open /dev/urandom");
        file.read_exact(v).expect("failed to read /dev/urandom")
    }
```
I inspected the HashMap implementation and have not found a way to work around it.
However, the weird thing is that you were telling me something about Firecracker blocking if no entropy were found. This should not happen since the getrandom syscall is called with nonblocking flag:
```libc::syscall(libc::SYS_getrandom, buf.as_mut_ptr(), buf.len(), libc::GRND_NONBLOCK)```.
Seems like (from the code pasted above) the way to go is to have the `urandom` device available? Is that a feasible solution for you?

**Comment by dianpopa** [comment]
#1434 removed last rand dependency.
