### ISSUE TITLE
PR status checks hard to interpret

### ISSUE THREAD

**Issue by blitz** [firecracker-microvm/firecracker#973]
When the status check for a pull request fails, it's hard to decipher from the thousands of lines of log output what is actually the problem.

One solution would be to have multiple individual status checks for unit tests, integration tests, rust formatting, python formatting.. The user could then click on the red X and get the report for the one check that failed.

**Comment by raduweiss** [comment]
That's definitely something we need to do (along with running said individual checks run in parallel, since the total time is too long now).

It's something we have in the backlog and will probably prioritize with the next couple of months.

Actually, we're also thinking about making our medium-term plans more transparent, and this might be a good catalyst 🙂; stay tuned.

**Comment by raduweiss** [comment]
Added to the roadmap as part of #1181.

**Comment by dianpopa** [comment]
Hi @blitz ,

Our PR status check had undergone significant improvements. Please take a look and let us know what you think!

**Comment by blitz** [comment]
@dianpopa Indeed. Looks far nicer now. Thanks!
